ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/http/src/server.cpp File Reference
server.cpp File Reference
#include <http_module.hpp>
#include <iostream>
Macros
#define CHECK_FUNC_RETURN_VAL_FOR_REQ(val)
Typedefs
using HttpMethod_t = Server &(Server::*)(const std::string &, Server::Handler)
Functions
Value http_create_server (std::vector< Value > &n, Ark::VM *vm)
Value handle_request_for (std::string_view funcname, HttpMethod_t handler, std::vector< Value > &n, Ark::VM *vm)
Value http_server_get (std::vector< Value > &n, Ark::VM *vm)
Value http_server_post (std::vector< Value > &n, Ark::VM *vm)
Value http_server_put (std::vector< Value > &n, Ark::VM *vm)
Value http_server_delete (std::vector< Value > &n, Ark::VM *vm)
Value http_server_stop (std::vector< Value > &n, Ark::VM *vm)
Value http_server_listen (std::vector< Value > &n, Ark::VM *vm)
Value http_server_set_mount_point (std::vector< Value > &n, Ark::VM *vm)
Value http_server_remove_mount_point (std::vector< Value > &n, Ark::VM *vm)
Value http_server_set_fext_mimetype (std::vector< Value > &n, Ark::VM *vm)
Value http_server_enable_logger (std::vector< Value > &n, Ark::VM *vm)
Macro Definition Documentation
CHECK_FUNC_RETURN_VAL_FOR_REQ
#define CHECK_FUNC_RETURN_VAL_FOR_REQ (val)
Value:
    (val.valueType() == ValueType::List && val.list().size() == 3 && \
     val.list()[0].valueType() == ValueType::Number &&               \
     val.list()[1].valueType() == ValueType::String &&               \
     val.list()[2].valueType() == ValueType::String)
Definition at line 5 of file server.cpp.
Typedef Documentation
HttpMethod_t
using HttpMethod_t = Server& (Server::*)(const std::string&, Server::Handler)
Definition at line 17 of file server.cpp.
Function Documentation
handle_request_for()
Value handle_request_for (std::string_view funcname, HttpMethod_t handler, std::vector< Value > & n, Ark::VM * vm)
Definition at line 19 of file server.cpp.
References CHECK_FUNC_RETURN_VAL_FOR_REQ, create_server(), get_cfs_param(), get_params(), Ark::Value::list(), Ark::Nil, Ark::Value::push_back(), Ark::VM::resolve(), and typecheck().
Referenced by http_server_delete(), http_server_get(), http_server_post(), and http_server_put().
http_create_server()
Value http_create_server (std::vector< Value > & n, Ark::VM * vm)
Definition at line 11 of file server.cpp.
References create_server(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_server_delete()
Value http_server_delete (std::vector< Value > & n, Ark::VM * vm)
Definition at line 99 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_enable_logger()
Value http_server_enable_logger (std::vector< Value > & n, Ark::VM * vm)
Definition at line 175 of file server.cpp.
References Ark::types::check(), Ark::types::generateError(), get_logger_level(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_server_get()
Value http_server_get (std::vector< Value > & n, Ark::VM * vm)
Definition at line 84 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_listen()
Value http_server_listen (std::vector< Value > & n, Ark::VM * vm)
Definition at line 110 of file server.cpp.
References Ark::types::check(), create_server(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_server_post()
Value http_server_post (std::vector< Value > & n, Ark::VM * vm)
Definition at line 89 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_put()
Value http_server_put (std::vector< Value > & n, Ark::VM * vm)
Definition at line 94 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_remove_mount_point()
Value http_server_remove_mount_point (std::vector< Value > & n, Ark::VM * vm)
Definition at line 147 of file server.cpp.
References Ark::types::check(), create_server(), Ark::False, Ark::types::generateError(), and Ark::True.
Referenced by getFunctionsMapping().
http_server_set_fext_mimetype()
Value http_server_set_fext_mimetype (std::vector< Value > & n, Ark::VM * vm)
Definition at line 161 of file server.cpp.
References Ark::types::check(), create_server(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_server_set_mount_point()
Value http_server_set_mount_point (std::vector< Value > & n, Ark::VM * vm)
Definition at line 132 of file server.cpp.
References Ark::types::check(), create_server(), Ark::False, Ark::types::generateError(), and Ark::True.
Referenced by getFunctionsMapping().
http_server_stop()
Value http_server_stop (std::vector< Value > & n, Ark::VM * vm)
Definition at line 104 of file server.cpp.
References create_server(), and Ark::Nil.
Referenced by getFunctionsMapping().