ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/json/src/main.cpp File Reference
main.cpp File Reference
#include <Ark/Module.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <memory>
Namespaces
namespace json
Functions
std::vector< std::unique_ptr< nlohmann::json > > & json::get_json_object ()
UserType::ControlFuncs * json::get_cfs ()
Value json::open (std::vector< Value > &args, Ark::VM *vm)
Value json::fromString (std::vector< Value > &args, Ark::VM *vm)
Value json::jsonToArk (nlohmann::json &obj)
Value json::get (std::vector< Value > &args, Ark::VM *vm)
Value json::toString (std::vector< Value > &args, Ark::VM *vm)
nlohmann::json json::listToJson (std::vector< Value > &arkList)
Value json::jset (std::vector< Value > &args, Ark::VM *vm)
Value json::write (std::vector< Value > &args, Ark::VM *vm)
Value json::fromList (std::vector< Value > &args, Ark::VM *vm)
Value json::len (std::vector< Value > &args, Ark::VM *vm)
ARK_API mapping * getFunctionsMapping ()
Function Documentation
getFunctionsMapping()
ARK_API mapping * getFunctionsMapping ()
Definition at line 329 of file main.cpp.
References json::fromList(), json::fromString(), json::get(), json::jset(), json::len(), mapping_add(), mapping_create(), json::open(), json::toString(), and json::write().