ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/http/include/http_module.hpp File Reference
http_module.hpp File Reference
#include <httplib.h>
#include <Ark/Module.hpp>
#include <vector>
#include <string>
#include <memory>
#include <list>
Macros
#define CPPHTTPLIB_OPENSSL_SUPPORT
Functions
std::list< Params > & get_params ()
std::list< Headers > & get_headers ()
std::list< Client > & get_clients ()
int & get_logger_level ()
bool & get_error_handler ()
Server & create_server ()
UserType::ControlFuncs * get_cfs_client ()
UserType::ControlFuncs * get_cfs_header ()
UserType::ControlFuncs * get_cfs_param ()
void typecheck (std::string_view funcname, const std::vector< Value > &n)
Value http_create_server (std::vector< Value > &n, Ark::VM *vm)
Value http_server_get (std::vector< Value > &n, Ark::VM *vm)
Value http_server_post (std::vector< Value > &n, Ark::VM *vm)
Value http_server_put (std::vector< Value > &n, Ark::VM *vm)
Value http_server_delete (std::vector< Value > &n, Ark::VM *vm)
Value http_server_stop (std::vector< Value > &n, Ark::VM *vm)
Value http_server_listen (std::vector< Value > &n, Ark::VM *vm)
Value http_server_set_mount_point (std::vector< Value > &n, Ark::VM *vm)
Value http_server_remove_mount_point (std::vector< Value > &n, Ark::VM *vm)
Value http_server_set_fext_mimetype (std::vector< Value > &n, Ark::VM *vm)
Value http_server_enable_logger (std::vector< Value > &n, Ark::VM *vm)
Value http_create_headers (std::vector< Value > &n, Ark::VM *vm)
Value http_create_client (std::vector< Value > &n, Ark::VM *vm)
Value http_client_get (std::vector< Value > &n, Ark::VM *vm)
Value http_create_params (std::vector< Value > &n, Ark::VM *vm)
Value http_params_tolist (std::vector< Value > &n, Ark::VM *vm)
Value http_client_post (std::vector< Value > &n, Ark::VM *vm)
Value http_client_put (std::vector< Value > &n, Ark::VM *vm)
Value http_client_delete (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_follow_location (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_co_timeout (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_read_timeout (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_write_timeout (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_basic_auth (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_bearer_token_auth (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_keep_alive (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_proxy (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_proxy_basic_auth (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_proxy_bearer_token_auth (std::vector< Value > &n, Ark::VM *vm)
Macro Definition Documentation
CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_OPENSSL_SUPPORT
Definition at line 5 of file http_module.hpp.
Function Documentation
create_server()
Server & create_server ()
Definition at line 41 of file utils.cpp.
References get_error_handler(), and get_logger_level().
Referenced by handle_request_for(), http_create_server(), http_server_listen(), http_server_remove_mount_point(), http_server_set_fext_mimetype(), http_server_set_mount_point(), and http_server_stop().
get_cfs_client()
UserType::ControlFuncs * get_cfs_client ()
Definition at line 78 of file utils.cpp.
References Ark::UserType::ControlFuncs::deleter, get_clients(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by http_create_client().
get_cfs_header()
UserType::ControlFuncs * get_cfs_header ()
Definition at line 99 of file utils.cpp.
References Ark::UserType::ControlFuncs::deleter, get_headers(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by http_create_headers().
get_cfs_param()
UserType::ControlFuncs * get_cfs_param ()
Definition at line 123 of file utils.cpp.
References Ark::UserType::ControlFuncs::deleter, get_params(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by handle_request_for(), and http_create_params().
get_clients()
std::list< Client > & get_clients ()
Definition at line 23 of file utils.cpp.
Referenced by get_cfs_client(), and http_create_client().
get_error_handler()
bool & get_error_handler ()
Definition at line 35 of file utils.cpp.
Referenced by create_server().
get_headers()
std::list< Headers > & get_headers ()
Definition at line 17 of file utils.cpp.
Referenced by get_cfs_header(), and http_create_headers().
get_logger_level()
int & get_logger_level ()
Definition at line 29 of file utils.cpp.
Referenced by create_server(), and http_server_enable_logger().
get_params()
std::list< Params > & get_params ()
Definition at line 11 of file utils.cpp.
Referenced by get_cfs_param(), handle_request_for(), and http_create_params().
http_client_delete()
Value http_client_delete (std::vector< Value > & n, Ark::VM * vm)
Definition at line 272 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_get()
Value http_client_get (std::vector< Value > & n, Ark::VM * vm)
Definition at line 44 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_post()
Value http_client_post (std::vector< Value > & n, Ark::VM * vm)
Definition at line 124 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_put()
Value http_client_put (std::vector< Value > & n, Ark::VM * vm)
Definition at line 198 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_set_basic_auth()
Value http_client_set_basic_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 389 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_bearer_token_auth()
Value http_client_set_bearer_token_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 405 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_co_timeout()
Value http_client_set_co_timeout (std::vector< Value > & n, Ark::VM * vm)
Definition at line 338 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_follow_location()
Value http_client_set_follow_location (std::vector< Value > & n, Ark::VM * vm)
Definition at line 325 of file client.cpp.
References Ark::types::check(), Ark::False, Ark::types::generateError(), Ark::Nil, and Ark::True.
Referenced by getFunctionsMapping().
http_client_set_keep_alive()
Value http_client_set_keep_alive (std::vector< Value > & n, Ark::VM * vm)
Definition at line 418 of file client.cpp.
References Ark::types::check(), Ark::False, Ark::types::generateError(), Ark::Nil, and Ark::True.
Referenced by getFunctionsMapping().
http_client_set_proxy()
Value http_client_set_proxy (std::vector< Value > & n, Ark::VM * vm)
Definition at line 433 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_proxy_basic_auth()
Value http_client_set_proxy_basic_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 447 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_proxy_bearer_token_auth()
Value http_client_set_proxy_bearer_token_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 464 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_read_timeout()
Value http_client_set_read_timeout (std::vector< Value > & n, Ark::VM * vm)
Definition at line 355 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_write_timeout()
Value http_client_set_write_timeout (std::vector< Value > & n, Ark::VM * vm)
Definition at line 372 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_create_client()
Value http_create_client (std::vector< Value > & n, Ark::VM * vm)
Definition at line 30 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), get_cfs_client(), get_clients(), and json::toString().
Referenced by getFunctionsMapping().
http_create_headers()
Value http_create_headers (std::vector< Value > & n, Ark::VM * vm)
Definition at line 3 of file client.cpp.
References get_cfs_header(), and get_headers().
Referenced by getFunctionsMapping().
http_create_params()
Value http_create_params (std::vector< Value > & n, Ark::VM * vm)
Definition at line 77 of file client.cpp.
References get_cfs_param(), and get_params().
Referenced by getFunctionsMapping().
http_create_server()
Value http_create_server (std::vector< Value > & n, Ark::VM * vm)
Definition at line 11 of file server.cpp.
References create_server(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_params_tolist()
Value http_params_tolist (std::vector< Value > & n, Ark::VM * vm)
Definition at line 104 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_server_delete()
Value http_server_delete (std::vector< Value > & n, Ark::VM * vm)
Definition at line 99 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_enable_logger()
Value http_server_enable_logger (std::vector< Value > & n, Ark::VM * vm)
Definition at line 175 of file server.cpp.
References Ark::types::check(), Ark::types::generateError(), get_logger_level(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_server_get()
Value http_server_get (std::vector< Value > & n, Ark::VM * vm)
Definition at line 84 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_listen()
Value http_server_listen (std::vector< Value > & n, Ark::VM * vm)
Definition at line 110 of file server.cpp.
References Ark::types::check(), create_server(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_server_post()
Value http_server_post (std::vector< Value > & n, Ark::VM * vm)
Definition at line 89 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_put()
Value http_server_put (std::vector< Value > & n, Ark::VM * vm)
Definition at line 94 of file server.cpp.
References handle_request_for().
Referenced by getFunctionsMapping().
http_server_remove_mount_point()
Value http_server_remove_mount_point (std::vector< Value > & n, Ark::VM * vm)
Definition at line 147 of file server.cpp.
References Ark::types::check(), create_server(), Ark::False, Ark::types::generateError(), and Ark::True.
Referenced by getFunctionsMapping().
http_server_set_fext_mimetype()
Value http_server_set_fext_mimetype (std::vector< Value > & n, Ark::VM * vm)
Definition at line 161 of file server.cpp.
References Ark::types::check(), create_server(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_server_set_mount_point()
Value http_server_set_mount_point (std::vector< Value > & n, Ark::VM * vm)
Definition at line 132 of file server.cpp.
References Ark::types::check(), create_server(), Ark::False, Ark::types::generateError(), and Ark::True.
Referenced by getFunctionsMapping().
http_server_stop()
Value http_server_stop (std::vector< Value > & n, Ark::VM * vm)
Definition at line 104 of file server.cpp.
References create_server(), and Ark::Nil.
Referenced by getFunctionsMapping().
typecheck()
void typecheck (std::string_view funcname, const std::vector< Value > & n)
Definition at line 147 of file utils.cpp.
References Ark::types::generateError().
Referenced by handle_request_for().