ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/hash/src/main.cpp File Reference
main.cpp File Reference
#include <picosha2.h>
#include <md5.hpp>
#include <Ark/Module.hpp>
Namespaces
namespace ArkHash
Functions
Value ArkHash::sha2 (std::vector< Value > &n, Ark::VM *vm)
Value ArkHash::md5 (std::vector< Value > &n, Ark::VM *vm)
ARK_API mapping * getFunctionsMapping ()
Function Documentation
getFunctionsMapping()
ARK_API mapping * getFunctionsMapping ()
Definition at line 35 of file main.cpp.
References mapping_add(), mapping_create(), ArkHash::md5(), and ArkHash::sha2().