ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/include/Ark/Module.hpp File Reference
Module.hpp File Reference
#include <Ark/VM/VM.hpp>
#include <Ark/Platform.hpp>
#include <Ark/TypeChecker.hpp>
Classes
struct mapping
Macros
#define ARK_API extern "C"
Functions
mapping * mapping_create (std::size_t len)
void mapping_add (mapping &map, const std::string &name, Value(*val)(std::vector< Value > &, Ark::VM *))
Macro Definition Documentation
ARK_API
#define ARK_API extern "C"
Definition at line 48 of file Module.hpp.
Function Documentation
mapping_add()
void mapping_add (mapping & map, const std::string & name, Value(*)(std::vector< Value > &, Ark::VM *) val) inline
Definition at line 25 of file Module.hpp.
References mapping::name, and mapping::value.
Referenced by getFunctionsMapping().
mapping_create()
mapping * mapping_create (std::size_t len) inline
Definition at line 17 of file Module.hpp.
References json::len(), mapping::name, and mapping::value.
Referenced by getFunctionsMapping().