ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/http/src/client.cpp File Reference
client.cpp File Reference
#include <http_module.hpp>
Functions
Value http_create_headers (std::vector< Value > &n, Ark::VM *vm)
Value http_create_client (std::vector< Value > &n, Ark::VM *vm)
Value http_client_get (std::vector< Value > &n, Ark::VM *vm)
Value http_create_params (std::vector< Value > &n, Ark::VM *vm)
Value http_params_tolist (std::vector< Value > &n, Ark::VM *vm)
Value http_client_post (std::vector< Value > &n, Ark::VM *vm)
Value http_client_put (std::vector< Value > &n, Ark::VM *vm)
Value http_client_delete (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_follow_location (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_co_timeout (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_read_timeout (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_write_timeout (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_basic_auth (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_bearer_token_auth (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_keep_alive (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_proxy (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_proxy_basic_auth (std::vector< Value > &n, Ark::VM *vm)
Value http_client_set_proxy_bearer_token_auth (std::vector< Value > &n, Ark::VM *vm)
Function Documentation
http_client_delete()
Value http_client_delete (std::vector< Value > & n, Ark::VM * vm)
Definition at line 272 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_get()
Value http_client_get (std::vector< Value > & n, Ark::VM * vm)
Definition at line 44 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_post()
Value http_client_post (std::vector< Value > & n, Ark::VM * vm)
Definition at line 124 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_put()
Value http_client_put (std::vector< Value > & n, Ark::VM * vm)
Definition at line 198 of file client.cpp.
References Ark::Nil, and Ark::Value::push_back().
Referenced by getFunctionsMapping().
http_client_set_basic_auth()
Value http_client_set_basic_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 389 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_bearer_token_auth()
Value http_client_set_bearer_token_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 405 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_co_timeout()
Value http_client_set_co_timeout (std::vector< Value > & n, Ark::VM * vm)
Definition at line 338 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_follow_location()
Value http_client_set_follow_location (std::vector< Value > & n, Ark::VM * vm)
Definition at line 325 of file client.cpp.
References Ark::types::check(), Ark::False, Ark::types::generateError(), Ark::Nil, and Ark::True.
Referenced by getFunctionsMapping().
http_client_set_keep_alive()
Value http_client_set_keep_alive (std::vector< Value > & n, Ark::VM * vm)
Definition at line 418 of file client.cpp.
References Ark::types::check(), Ark::False, Ark::types::generateError(), Ark::Nil, and Ark::True.
Referenced by getFunctionsMapping().
http_client_set_proxy()
Value http_client_set_proxy (std::vector< Value > & n, Ark::VM * vm)
Definition at line 433 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_proxy_basic_auth()
Value http_client_set_proxy_basic_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 447 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_proxy_bearer_token_auth()
Value http_client_set_proxy_bearer_token_auth (std::vector< Value > & n, Ark::VM * vm)
Definition at line 464 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_read_timeout()
Value http_client_set_read_timeout (std::vector< Value > & n, Ark::VM * vm)
Definition at line 355 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_client_set_write_timeout()
Value http_client_set_write_timeout (std::vector< Value > & n, Ark::VM * vm)
Definition at line 372 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().
http_create_client()
Value http_create_client (std::vector< Value > & n, Ark::VM * vm)
Definition at line 30 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), get_cfs_client(), get_clients(), and json::toString().
Referenced by getFunctionsMapping().
http_create_headers()
Value http_create_headers (std::vector< Value > & n, Ark::VM * vm)
Definition at line 3 of file client.cpp.
References get_cfs_header(), and get_headers().
Referenced by getFunctionsMapping().
http_create_params()
Value http_create_params (std::vector< Value > & n, Ark::VM * vm)
Definition at line 77 of file client.cpp.
References get_cfs_param(), and get_params().
Referenced by getFunctionsMapping().
http_params_tolist()
Value http_params_tolist (std::vector< Value > & n, Ark::VM * vm)
Definition at line 104 of file client.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Value::push_back().
Referenced by getFunctionsMapping().