.TH "Ark::OptimizerError" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ark::OptimizerError \- \fBOptimizerError\fP thrown by the AST optimizer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions\&.hpp>\fP
.PP
Inherits exception\&.
.SH "Detailed Description"
.PP 
\fBOptimizerError\fP thrown by the AST optimizer\&. 
.PP
Definition at line 136 of file Exceptions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
