.TH "Ark::Logger" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ark::Logger \- A basic logger\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Log\&.hpp>\fP
.SH "Detailed Description"
.PP 
A basic logger\&. 
.PP
Definition at line 48 of file Log\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
