.TH "Ark::internal::CValue" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ark::internal::CValue \- A \fBCompiler\fP Value class helper to handle multiple types\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CValue\&.hpp>\fP
.SH "Detailed Description"
.PP 
A \fBCompiler\fP Value class helper to handle multiple types\&. 
.PP
Definition at line 37 of file CValue\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
