.TH "Ark::UserType::ControlFuncs" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ark::UserType::ControlFuncs \- A structure holding a bunch of pointers to different useful functions related to this usertype\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UserType\&.hpp>\fP
.SH "Detailed Description"
.PP 
A structure holding a bunch of pointers to different useful functions related to this usertype\&. 
.PP
Definition at line 36 of file UserType\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
