.TH "include/Ark/Compiler/BytecodeReader.hpp" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Ark/Compiler/BytecodeReader.hpp \- A bytecode disassembler for ArkScript\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cinttypes>\fP
.br
\fC#include <Ark/Config\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArk::BytecodeReader\fP"
.br
.RI "\fIThis class is just a helper to\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A bytecode disassembler for ArkScript\&. 


.PP
\fBAuthor:\fP
.RS 4
Alexandre Plateau (lexplt.dev@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-10-27
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.PP
Definition in file \fBBytecodeReader\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
