.TH "include/Ark Directory Reference" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Ark Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBuiltins\fP"
.br
.ti -1c
.RI "directory \fBCompiler\fP"
.br
.ti -1c
.RI "directory \fBREPL\fP"
.br
.ti -1c
.RI "directory \fBVM\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArk\&.hpp\fP"
.br
.RI "\fIIncludes the needed files to start using ArkScript\&. \fP"
.ti -1c
.RI "file \fBConfig\&.hpp\fP"
.br
.RI "\fIArkScript configuration macros\&. \fP"
.ti -1c
.RI "file \fBConstants\&.hpp\fP"
.br
.ti -1c
.RI "file \fBExceptions\&.hpp\fP"
.br
.RI "\fIArkScript homemade exceptions\&. \fP"
.ti -1c
.RI "file \fBLog\&.hpp\fP"
.br
.RI "\fIArkScript logger\&. \fP"
.ti -1c
.RI "file \fBProfiling\&.hpp\fP"
.br
.ti -1c
.RI "file \fBUtils\&.hpp\fP"
.br
.RI "\fILots of utilities about string, filesystem and more\&. \fP"
.in -1c
