.TH "include/Ark/Compiler Directory Reference" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Ark/Compiler Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBytecodeReader\&.hpp\fP"
.br
.RI "\fIA bytecode disassembler for ArkScript\&. \fP"
.ti -1c
.RI "file \fBCompiler\&.hpp\fP"
.br
.RI "\fIArkScript compiler is in charge of transforming the AST into bytecode\&. \fP"
.ti -1c
.RI "file \fBCValue\&.hpp\fP"
.br
.RI "\fIThe basic value type handled by the compiler\&. \fP"
.ti -1c
.RI "file \fBInstructions\&.hpp\fP"
.br
.RI "\fIThe different instructions used by the compiler and virtual machine\&. \fP"
.ti -1c
.RI "file \fBLexer\&.hpp\fP"
.br
.RI "\fITokenize ArkScript code\&. \fP"
.ti -1c
.RI "file \fBNode\&.hpp\fP"
.br
.RI "\fIAST node used by the parser, optimizer and compiler\&. \fP"
.ti -1c
.RI "file \fBOptimizer\&.hpp\fP"
.br
.RI "\fIOptimizes a given ArkScript AST\&. \fP"
.ti -1c
.RI "file \fBParser\&.hpp\fP"
.br
.RI "\fIParses a token stream into an AST by using the \fBArk::internal::Node\fP\&. \fP"
.in -1c
