.TH "src/Builtins Directory Reference" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Builtins Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuiltins\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIO\&.cpp\fP"
.br
.ti -1c
.RI "file \fBList\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMathematics\&.cpp\fP"
.br
.ti -1c
.RI "file \fBString\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSystem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTime\&.cpp\fP"
.br
.in -1c
