.TH "include/Ark/Builtins Directory Reference" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Ark/Builtins Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuiltins\&.hpp\fP"
.br
.RI "\fIHost the declaration of all the ArkScript builtins\&. \fP"
.in -1c
