.TH "include/Ark/REPL/ConsoleStyle.hpp" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Ark/REPL/ConsoleStyle.hpp \- Colors per token used by replxx\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <replxx\&.hxx>\fP
.br

.SH "Detailed Description"
.PP 
Colors per token used by replxx\&. 


.PP
\fBAuthor:\fP
.RS 4
Alexandre Plateau (lexplt.dev@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-10-27
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.PP
Definition in file \fBConsoleStyle\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
