.TH "include/Ark/Utils.hpp" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Ark/Utils.hpp \- Lots of utilities about string, filesystem and more\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <streambuf>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <regex>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <Ark/Constants\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::string \fBArk::Utils::toString\fP (T &&object)"
.br
.RI "\fIHome made version of std::to_string to convert to string anything which has an operator<< for this\&. \fP"
.ti -1c
.RI "void \fBArk::Utils::stringReplaceAll\fP (std::string &source, const std::string &from, const std::string &to)"
.br
.RI "\fIReplaces all occurence of \fCfrom\fP to \fCto\fP in \fCsource\fP \fP"
.ti -1c
.RI "std::vector< std::string > \fBArk::Utils::splitString\fP (const std::string &source, char sep)"
.br
.RI "\fICut a string into pieces, given a character separator\&. \fP"
.ti -1c
.RI "bool \fBArk::Utils::isInteger\fP (const std::string &s)"
.br
.RI "\fIChecks if a string represents a valid integer\&. \fP"
.ti -1c
.RI "bool \fBArk::Utils::isFloat\fP (const std::string &s)"
.br
.RI "\fIChecks if a string represents a valid floating point number\&. \fP"
.ti -1c
.RI "bool \fBArk::Utils::isFraction\fP (const std::string &s)"
.br
.RI "\fIChecks if a string represents a valid fractional number\&. \fP"
.ti -1c
.RI "bool \fBArk::Utils::isDouble\fP (const std::string &s, double *output=nullptr)"
.br
.RI "\fIChecks if a string is a valid double\&. \fP"
.ti -1c
.RI "bool \fBArk::Utils::fileExists\fP (const std::string &name) noexcept"
.br
.RI "\fIChecks if a file exists\&. \fP"
.ti -1c
.RI "std::string \fBArk::Utils::readFile\fP (const std::string &name)"
.br
.RI "\fIHelper to read a file\&. \fP"
.ti -1c
.RI "std::string \fBArk::Utils::getDirectoryFromPath\fP (const std::string &path)"
.br
.RI "\fIGet the directory from a path\&. \fP"
.ti -1c
.RI "std::string \fBArk::Utils::getFilenameFromPath\fP (const std::string &path)"
.br
.RI "\fIGet the filename from a path\&. \fP"
.ti -1c
.RI "std::string \fBArk::Utils::canonicalRelPath\fP (const std::string &path)"
.br
.RI "\fIGet the canonical relative path from a path\&. \fP"
.ti -1c
.RI "int \fBArk::Utils::dec_places\fP (double d)"
.br
.RI "\fICount the number of decimals for a double\&. \fP"
.ti -1c
.RI "int \fBArk::Utils::dig_places\fP (double d)"
.br
.RI "\fICount the number of digits for a double\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Lots of utilities about string, filesystem and more\&. 


.PP
\fBAuthor:\fP
.RS 4
Alexandre Plateau (lexplt.dev@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-10-27
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.PP
Definition in file \fBUtils\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
