.TH "include/Ark/REPL/replxx/Util.hpp" 3 "Wed Dec 30 2020" "ArkScript" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Ark/REPL/replxx/Util.hpp \- replxx utilities  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <string>\fP
.br
\fC#include <replxx\&.hxx>\fP
.br

.SH "Detailed Description"
.PP 
replxx utilities 


.PP
\fBAuthor:\fP
.RS 4
Alexandre Plateau (lexplt.dev@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2020-10-27
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020 
.RE
.PP

.PP
Definition in file \fBUtil\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArkScript from the source code\&.
