ArkScript: Ark::Parser Class Reference
Ark::Parser Class Reference
The parser is responsible of constructing the Abstract Syntax Tree from a token list.
#include <Parser.hpp>
Public Member Functions
Parser (unsigned debug, const std::string &lib_dir, uint16_t options) noexcept
Construct a new Parser object.
void feed (const std::string &code, const std::string &filename=ARK_NO_NAME_FILE)
Give the code to parse.
const internal::Node & ast () const noexcept
Return the generated AST.
const std::vector< std::string > & getImports () const noexcept
Return the list of files imported by the code given to the parser.
Private Member Functions
void sugar (std::vector< internal::Token > &tokens) noexcept
Applying syntactic sugar: {...} => (begin...), [...] => (list ...)
internal::Node parse (std::list< internal::Token > &tokens, bool authorize_capture=false, bool authorize_field_read=false, bool in_macro=false)
Parse a list of tokens recursively.
void parseIf (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseLetMut (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseSet (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseFun (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseWhile (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseBegin (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseImport (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseQuote (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void parseDel (internal::Node &, internal::Token &, std::list< internal::Token > &, bool, bool, bool)
internal::Node parseShorthand (internal::Token &, std::list< internal::Token > &, bool, bool, bool)
void checkForInvalidTokens (internal::Node &, internal::Token &, bool, bool, bool)
internal::Token nextToken (std::list< internal::Token > &tokens)
Get the next token if possible, from a list of tokens.
internal::Node atom (const internal::Token &token)
Convert a token to a node.
bool checkForInclude (internal::Node &n, internal::Node &parent, std::size_t pos=0)
Search for all the includes in a given node, in its sub-nodes and replace them by the code of the included file.
std::string seekFile (const std::string &file)
Seek a file in the lib folder and everywhere.
void expect (bool pred, const std::string &message, internal::Token token)
Throw a parse exception is the given predicated is false.
void throwParseError (const std::string &message, internal::Token token)
Throw a parse error related to a token (seek it in the related file and highlight the error)
void throwParseError_ (const std::string &message)
Throw a parse error unrelated to any token.
Private Attributes
unsigned m_debug
std::string m_libdir
uint16_t m_options
internal::Lexer m_lexer
internal::Node m_ast
internal::Token m_last_token
std::string m_file
std::string m_code
std::vector< std::string > m_parent_include
Friends
ARK_API std::ostream & operator<< (std::ostream &os, const Parser &P) noexcept
Detailed Description
The parser is responsible of constructing the Abstract Syntax Tree from a token list.
Definition at line 35 of file Parser.hpp.
Constructor & Destructor Documentation
Parser()
Ark::Parser::Parser (unsigned debug, const std::string & lib_dir, uint16_t options) noexcept
Construct a new Parser object.
Parameters
debug the debug level
lib_dir the path to the standard library
options the parsing options
Definition at line 13 of file Parser.cpp.
Member Function Documentation
ast()
const Node & Ark::Parser::ast () const noexcept
Return the generated AST.
Returns
const internal::Node&
Definition at line 59 of file Parser.cpp.
References m_ast.
Referenced by checkForInclude(), and Ark::Compiler::feed().
atom()
Node Ark::Parser::atom (const internal::Token & token) private
Convert a token to a node.
Parameters
token the token to converts
Returns
internal::Node
Definition at line 400 of file Parser.cpp.
References Ark::internal::Token::col, Ark::internal::Token::line, m_file, Ark::internal::Node::setString(), throwParseError(), Ark::internal::Token::token, and Ark::internal::Token::type.
Referenced by parse(), parseDel(), parseIf(), parseImport(), parseLetMut(), parseSet(), and parseWhile().
checkForInclude()
bool Ark::Parser::checkForInclude (internal::Node & n, internal::Node & parent, std::size_t pos = 0) private
Search for all the includes in a given node, in its sub-nodes and replace them by the code of the included file.
Parameters
n
parent the parent node of the current one
pos the position of the child node in the parent node list
Returns
true if we found an import and replaced it by the corresponding code
Definition at line 469 of file Parser.cpp.
References ast(), Ark::Utils::canonicalRelPath(), checkForInclude(), Ark::internal::Node::constList(), feed(), Ark::internal::Node::keyword(), Ark::internal::Node::list(), m_debug, m_file, m_libdir, m_options, m_parent_include, Ark::internal::Node::nodeType(), Ark::Utils::readFile(), and seekFile().
Referenced by checkForInclude(), and feed().
checkForInvalidTokens()
void Ark::Parser::checkForInvalidTokens (internal::Node & atomized, internal::Token & token, bool previous_token_was_lparen, bool authorize_capture, bool authorize_field_read) private
Definition at line 366 of file Parser.cpp.
References Ark::internal::Node::nodeType(), and throwParseError().
Referenced by parse().
expect()
void Ark::Parser::expect (bool pred, const std::string & message, internal::Token token) inline private
Throw a parse exception is the given predicated is false.
Parameters
pred
message error message to use
token concerned token
Referenced by nextToken(), parse(), parseBegin(), parseDel(), parseFun(), parseIf(), parseImport(), parseLetMut(), parseQuote(), parseSet(), and parseWhile().
feed()
void Ark::Parser::feed (const std::string & code, const std::string & filename = ARK_NO_NAME_FILE)
Give the code to parse.
Parameters
code the ArkScript code
filename the name of the file
Definition at line 21 of file Parser.cpp.
References ARK_NO_NAME_FILE, Ark::Utils::canonicalRelPath(), checkForInclude(), Ark::internal::Lexer::feed(), Ark::internal::Node::list(), m_ast, m_code, m_debug, m_file, m_last_token, m_lexer, m_parent_include, parse(), Ark::internal::Node::setFilename(), sugar(), throwParseError_(), and Ark::internal::Lexer::tokens().
Referenced by checkForInclude(), and Ark::Compiler::feed().
getImports()
const std::vector< std::string > & Ark::Parser::getImports () const noexcept
Return the list of files imported by the code given to the parser.
Each path of each imported file is relative to the filename given when feeding the parser.
Returns
const std::vector<std::string>&
Definition at line 64 of file Parser.cpp.
References m_parent_include.
Referenced by Ark::Compiler::feed().
nextToken()
Token Ark::Parser::nextToken (std::list< internal::Token > & tokens) private
Get the next token if possible, from a list of tokens.
The list of tokens is modified.
Parameters
tokens list of tokens to get the next token from
Returns
internal::Token
Definition at line 390 of file Parser.cpp.
References expect(), and m_last_token.
Referenced by parse(), parseDel(), parseIf(), parseImport(), parseLetMut(), parseSet(), and parseWhile().
parse()
Node Ark::Parser::parse (std::list< internal::Token > & tokens, bool authorize_capture = false, bool authorize_field_read = false, bool in_macro = false) private
Parse a list of tokens recursively.
Parameters
tokens
authorize_capture if we are authorized to consume TokenType::Capture tokens
authorize_field_read if we are authorized to consume TokenType::GetField tokens
in_macro if we are in a macro, there a bunch of things we can tolerate
Returns
internal::Node
Definition at line 102 of file Parser.cpp.
References atom(), checkForInvalidTokens(), Ark::internal::Token::col, expect(), Ark::internal::Token::line, m_file, m_last_token, nextToken(), Ark::internal::Builtins::operators, parse(), parseBegin(), parseDel(), parseFun(), parseIf(), parseImport(), parseLetMut(), parseQuote(), parseSet(), parseShorthand(), parseWhile(), Ark::internal::Node::push_back(), throwParseError(), Ark::internal::Token::token, and Ark::internal::Token::type.
Referenced by feed(), parse(), parseBegin(), parseFun(), parseIf(), parseLetMut(), parseQuote(), parseSet(), parseShorthand(), and parseWhile().
parseBegin()
void Ark::Parser::parseBegin (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 295 of file Parser.cpp.
References expect(), m_last_token, parse(), and Ark::internal::Node::push_back().
Referenced by parse().
parseDel()
void Ark::Parser::parseDel (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 323 of file Parser.cpp.
References atom(), expect(), nextToken(), Ark::internal::Node::push_back(), and throwParseError().
Referenced by parse().
parseFun()
void Ark::Parser::parseFun (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 263 of file Parser.cpp.
References expect(), Ark::internal::Node::list(), m_last_token, parse(), Ark::internal::Node::push_back(), throwParseError(), and Ark::internal::Token::token.
Referenced by parse().
parseIf()
void Ark::Parser::parseIf (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 191 of file Parser.cpp.
References atom(), expect(), m_last_token, nextToken(), parse(), Ark::internal::Node::push_back(), and throwParseError().
Referenced by parse().
parseImport()
void Ark::Parser::parseImport (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 308 of file Parser.cpp.
References atom(), expect(), nextToken(), Ark::internal::Node::push_back(), and throwParseError().
Referenced by parse().
parseLetMut()
void Ark::Parser::parseLetMut (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 214 of file Parser.cpp.
References atom(), expect(), Ark::internal::Node::list(), m_last_token, nextToken(), parse(), Ark::internal::Node::push_back(), throwParseError(), and Ark::internal::Token::token.
Referenced by parse().
parseQuote()
void Ark::Parser::parseQuote (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 317 of file Parser.cpp.
References expect(), parse(), and Ark::internal::Node::push_back().
Referenced by parse().
parseSet()
void Ark::Parser::parseSet (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 237 of file Parser.cpp.
References atom(), expect(), Ark::internal::Node::list(), m_last_token, nextToken(), parse(), Ark::internal::Node::push_back(), throwParseError(), and Ark::internal::Token::token.
Referenced by parse().
parseShorthand()
Node Ark::Parser::parseShorthand (internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 332 of file Parser.cpp.
References Ark::internal::Token::col, Ark::internal::Token::line, Ark::internal::Node::list(), m_debug, m_file, Ark::internal::Node::nodeType(), parse(), Ark::internal::Node::push_back(), throwParseError(), and Ark::internal::Token::token.
Referenced by parse().
parseWhile()
void Ark::Parser::parseWhile (internal::Node & block, internal::Token & token, std::list< internal::Token > & tokens, bool authorize_capture, bool authorize_field_read, bool in_macro) private
Definition at line 278 of file Parser.cpp.
References atom(), expect(), Ark::internal::Node::list(), nextToken(), parse(), Ark::internal::Node::push_back(), throwParseError(), and Ark::internal::Token::token.
Referenced by parse().
seekFile()
std::string Ark::Parser::seekFile (const std::string & file) private
Seek a file in the lib folder and everywhere.
Parameters
file
Returns
std::string
Definition at line 538 of file Parser.cpp.
References Ark::Utils::fileExists(), Ark::Utils::getDirectoryFromPath(), Ark::Utils::getFilenameFromPath(), m_debug, m_file, and m_libdir.
Referenced by checkForInclude().
sugar()
void Ark::Parser::sugar (std::vector< internal::Token > & tokens) private noexcept
Applying syntactic sugar: {...} => (begin...), [...] => (list ...)
Parameters
tokens a list of tokens
Definition at line 69 of file Parser.cpp.
Referenced by feed().
throwParseError()
void Ark::Parser::throwParseError (const std::string & message, internal::Token token) inline private
Throw a parse error related to a token (seek it in the related file and highlight the error)
Parameters
message
token
Referenced by atom(), checkForInvalidTokens(), parse(), parseDel(), parseFun(), parseIf(), parseImport(), parseLetMut(), parseSet(), parseShorthand(), and parseWhile().
throwParseError_()
void Ark::Parser::throwParseError_ (const std::string & message) inline private
Throw a parse error unrelated to any token.
Parameters
message
Referenced by feed().
Friends And Related Function Documentation
operator<<
ARK_API std::ostream & operator<< (std::ostream & os, const Parser & P) friend
Definition at line 563 of file Parser.cpp.
Member Data Documentation
m_ast
internal::Node Ark::Parser::m_ast private
Definition at line 78 of file Parser.hpp.
Referenced by ast(), and feed().
m_code
std::string Ark::Parser::m_code private
Definition at line 84 of file Parser.hpp.
Referenced by feed().
m_debug
unsigned Ark::Parser::m_debug private
Definition at line 74 of file Parser.hpp.
Referenced by checkForInclude(), feed(), parseShorthand(), and seekFile().
m_file
std::string Ark::Parser::m_file private
Definition at line 82 of file Parser.hpp.
Referenced by atom(), checkForInclude(), feed(), parse(), parseShorthand(), and seekFile().
m_last_token
internal::Token Ark::Parser::m_last_token private
Definition at line 79 of file Parser.hpp.
Referenced by feed(), nextToken(), parse(), parseBegin(), parseFun(), parseIf(), parseLetMut(), and parseSet().
m_lexer
internal::Lexer Ark::Parser::m_lexer private
Definition at line 77 of file Parser.hpp.
Referenced by feed().
m_libdir
std::string Ark::Parser::m_libdir private
Definition at line 75 of file Parser.hpp.
Referenced by checkForInclude(), and seekFile().
m_options
uint16_t Ark::Parser::m_options private
Definition at line 76 of file Parser.hpp.
Referenced by checkForInclude().
m_parent_include
std::vector<std::string> Ark::Parser::m_parent_include private
Definition at line 86 of file Parser.hpp.
Referenced by checkForInclude(), feed(), and getImports().
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/include/Ark/Compiler/Parser.hpp
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/src/arkreactor/Compiler/Parser.cpp