ArkScript: Ark::internal::BaseParser Class Reference
Ark::internal::BaseParser Class Reference
#include <BaseParser.hpp>
Public Member Functions
BaseParser ()=default
Protected Member Functions
void initParser (const std::string &filename, const std::string &code)
FilePosition getCursor () const
void error (const std::string &error, std::string exp)
void errorWithNextToken (const std::string &message)
void errorMissingSuffix (char suffix, const std::string &node_name)
long getCount ()
std::size_t getSize () const
bool isEOF ()
void backtrack (long n)
bool accept (const CharPred &t, std::string *s=nullptr)
bool expect (const CharPred &t, std::string *s=nullptr)
bool space (std::string *s=nullptr)
bool inlineSpace (std::string *s=nullptr)
bool endOfLine (std::string *s=nullptr)
bool comment (std::string *s=nullptr)
bool spaceComment (std::string *s=nullptr)
bool newlineOrComment (std::string *s=nullptr)
bool prefix (char c)
bool suffix (char c)
bool number (std::string *s=nullptr)
bool signedNumber (std::string *s=nullptr)
bool hexNumber (unsigned length, std::string *s=nullptr)
bool name (std::string *s=nullptr)
bool sequence (const std::string &s)
bool packageName (std::string *s=nullptr)
bool anyUntil (const CharPred &delim, std::string *s=nullptr)
bool oneOf (std::initializer_list< std::string > words, std::string *s=nullptr)
Protected Attributes
std::string m_filename
Private Member Functions
void registerNewLine (std::string::iterator it, std::size_t row)
void next ()
Private Attributes
std::string m_str
std::vector< std::pair< std::string::iterator, std::size_t > > m_it_to_row
std::string::iterator m_it
std::string::iterator m_next_it
utf8_char_t m_sym
FilePosition m_filepos
Detailed Description
Definition at line 20 of file BaseParser.hpp.
Constructor & Destructor Documentation
BaseParser()
Ark::internal::BaseParser::BaseParser () default
Member Function Documentation
accept()
bool Ark::internal::BaseParser::accept (const CharPred & t, std::string * s = nullptr) protected
Definition at line 127 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::c_str(), Ark::internal::utf8_char_t::codepoint(), isEOF(), m_sym, and next().
Referenced by anyUntil(), Ark::internal::Parser::block(), comment(), endOfLine(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), hexNumber(), Ark::internal::Parser::import_(), inlineSpace(), Ark::internal::Parser::list(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), name(), number(), packageName(), prefix(), sequence(), signedNumber(), space(), and suffix().
anyUntil()
bool Ark::internal::BaseParser::anyUntil (const CharPred & delim, std::string * s = nullptr) protected
Definition at line 326 of file BaseParser.cpp.
References accept().
Referenced by errorWithNextToken().
backtrack()
void Ark::internal::BaseParser::backtrack (long n) protected
Definition at line 68 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::at(), Ark::internal::FilePosition::col, m_filepos, m_it, m_it_to_row, m_next_it, m_str, m_sym, and Ark::internal::FilePosition::row.
Referenced by Ark::internal::Parser::atom(), errorWithNextToken(), Ark::internal::Parser::function(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::macro(), Ark::internal::Parser::node(), and Ark::internal::Parser::run().
comment()
bool Ark::internal::BaseParser::comment (std::string * s = nullptr) protected
Definition at line 196 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::condition(), Ark::internal::Parser::del(), Ark::internal::Parser::function(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::list(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::macroCondition(), newlineOrComment(), Ark::internal::Parser::run(), spaceComment(), and Ark::internal::Parser::wrapped().
endOfLine()
bool Ark::internal::BaseParser::endOfLine (std::string * s = nullptr) protected
Definition at line 183 of file BaseParser.cpp.
References accept().
error()
void Ark::internal::BaseParser::error (const std::string & error, std::string exp) protected
Definition at line 105 of file BaseParser.cpp.
References error(), getCursor(), m_filename, and m_sym.
Referenced by error(), errorWithNextToken(), expect(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::import_(), and initParser().
errorMissingSuffix()
void Ark::internal::BaseParser::errorMissingSuffix (char suffix, const std::string & node_name) protected
Definition at line 122 of file BaseParser.cpp.
References errorWithNextToken(), and suffix().
Referenced by Ark::internal::Parser::wrapped().
errorWithNextToken()
void Ark::internal::BaseParser::errorWithNextToken (const std::string & message) protected
Definition at line 111 of file BaseParser.cpp.
References anyUntil(), backtrack(), error(), and getCount().
Referenced by Ark::internal::Parser::condition(), Ark::internal::Parser::del(), errorMissingSuffix(), Ark::internal::Parser::function(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::macroCondition(), and Ark::internal::Parser::run().
expect()
bool Ark::internal::BaseParser::expect (const CharPred & t, std::string * s = nullptr) protected
Definition at line 143 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::c_str(), Ark::internal::utf8_char_t::codepoint(), error(), m_sym, Ark::internal::CharPred::name, and next().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::list(), and Ark::internal::Parser::macro().
getCount()
long Ark::internal::BaseParser::getCount () inline protected
Definition at line 50 of file BaseParser.hpp.
Referenced by Ark::internal::Parser::atom(), errorWithNextToken(), Ark::internal::Parser::function(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::macro(), Ark::internal::Parser::node(), and Ark::internal::Parser::run().
getCursor()
FilePosition Ark::internal::BaseParser::getCursor () const protected
Definition at line 100 of file BaseParser.cpp.
References m_filepos.
Referenced by error(), Ark::internal::Parser::setNodePosAndFilename(), and Ark::internal::Parser::wrapped().
getSize()
std::size_t Ark::internal::BaseParser::getSize () const inline protected
Definition at line 51 of file BaseParser.hpp.
hexNumber()
bool Ark::internal::BaseParser::hexNumber (unsigned length, std::string * s = nullptr) protected
Definition at line 279 of file BaseParser.cpp.
References accept().
initParser()
void Ark::internal::BaseParser::initParser (const std::string & filename, const std::string & code) protected
Definition at line 50 of file BaseParser.cpp.
References error(), m_filename, m_it, m_next_it, m_str, m_sym, and next().
Referenced by Ark::internal::Parser::process().
inlineSpace()
bool Ark::internal::BaseParser::inlineSpace (std::string * s = nullptr) protected
Definition at line 169 of file BaseParser.cpp.
References accept().
Referenced by spaceComment().
isEOF()
bool Ark::internal::BaseParser::isEOF () inline protected
Definition at line 52 of file BaseParser.hpp.
Referenced by accept(), Ark::internal::Parser::block(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::list(), Ark::internal::Parser::macroArgs(), newlineOrComment(), next(), Ark::internal::Parser::run(), and spaceComment().
name()
bool Ark::internal::BaseParser::name (std::string * s = nullptr) protected
Definition at line 290 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::del(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), oneOf(), and Ark::internal::Parser::wrapped().
newlineOrComment()
bool Ark::internal::BaseParser::newlineOrComment (std::string * s = nullptr) protected
Definition at line 222 of file BaseParser.cpp.
References comment(), isEOF(), and space().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::condition(), Ark::internal::Parser::del(), Ark::internal::Parser::function(), Ark::internal::Parser::functionArgs(), Ark::internal::Parser::functionCall(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::list(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), Ark::internal::Parser::macroArgs(), Ark::internal::Parser::macroCondition(), Ark::internal::Parser::run(), and Ark::internal::Parser::wrapped().
next()
void Ark::internal::BaseParser::next () private
Definition at line 26 of file BaseParser.cpp.
References Ark::internal::utf8_char_t::at(), Ark::internal::FilePosition::col, isEOF(), Ark::internal::utf8_char_t::isPrintable(), m_filepos, m_it, m_next_it, m_sym, registerNewLine(), Ark::internal::FilePosition::row, and Ark::internal::utf8_char_t::size().
Referenced by accept(), expect(), initParser(), and registerNewLine().
number()
bool Ark::internal::BaseParser::number (std::string * s = nullptr) protected
Definition at line 248 of file BaseParser.cpp.
References accept().
Referenced by signedNumber().
oneOf()
bool Ark::internal::BaseParser::oneOf (std::initializer_list< std::string > words, std::string * s = nullptr) protected
Definition at line 337 of file BaseParser.cpp.
References name().
Referenced by Ark::internal::Parser::block(), Ark::internal::Parser::condition(), Ark::internal::Parser::del(), Ark::internal::Parser::function(), Ark::internal::Parser::import_(), Ark::internal::Parser::letMutSet(), Ark::internal::Parser::loop(), Ark::internal::Parser::macro(), and Ark::internal::Parser::macroCondition().
packageName()
bool Ark::internal::BaseParser::packageName (std::string * s = nullptr) protected
Definition at line 315 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::import_().
prefix()
bool Ark::internal::BaseParser::prefix (char c) protected
Definition at line 236 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::wrapped().
registerNewLine()
void Ark::internal::BaseParser::registerNewLine (std::string::iterator it, std::size_t row) private
Definition at line 6 of file BaseParser.cpp.
References m_it_to_row, m_str, and next().
Referenced by next().
sequence()
bool Ark::internal::BaseParser::sequence (const std::string & s) protected
Definition at line 304 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::macroArgs().
signedNumber()
bool Ark::internal::BaseParser::signedNumber (std::string * s = nullptr) protected
Definition at line 261 of file BaseParser.cpp.
References accept(), Ark::internal::IsMinus, and number().
space()
bool Ark::internal::BaseParser::space (std::string * s = nullptr) protected
Definition at line 155 of file BaseParser.cpp.
References accept().
Referenced by Ark::internal::Parser::import_(), and newlineOrComment().
spaceComment()
bool Ark::internal::BaseParser::spaceComment (std::string * s = nullptr) protected
Definition at line 208 of file BaseParser.cpp.
References comment(), inlineSpace(), and isEOF().
Referenced by Ark::internal::Parser::run(), and Ark::internal::Parser::wrapped().
suffix()
bool Ark::internal::BaseParser::suffix (char c) protected
Definition at line 243 of file BaseParser.cpp.
References accept().
Referenced by errorMissingSuffix(), and Ark::internal::Parser::wrapped().
Member Data Documentation
m_filename
std::string Ark::internal::BaseParser::m_filename protected
Definition at line 40 of file BaseParser.hpp.
Referenced by error(), initParser(), and Ark::internal::Parser::setNodePosAndFilename().
m_filepos
FilePosition Ark::internal::BaseParser::m_filepos private
Definition at line 30 of file BaseParser.hpp.
Referenced by backtrack(), getCursor(), and next().
m_it
std::string::iterator Ark::internal::BaseParser::m_it private
Definition at line 28 of file BaseParser.hpp.
Referenced by backtrack(), initParser(), and next().
m_it_to_row
std::vector<std::pair<std::string::iterator, std::size_t> > Ark::internal::BaseParser::m_it_to_row private
Definition at line 27 of file BaseParser.hpp.
Referenced by backtrack(), and registerNewLine().
m_next_it
std::string::iterator Ark::internal::BaseParser::m_next_it private
Definition at line 28 of file BaseParser.hpp.
Referenced by backtrack(), initParser(), and next().
m_str
std::string Ark::internal::BaseParser::m_str private
Definition at line 26 of file BaseParser.hpp.
Referenced by backtrack(), initParser(), and registerNewLine().
m_sym
utf8_char_t Ark::internal::BaseParser::m_sym private
Definition at line 29 of file BaseParser.hpp.
Referenced by accept(), backtrack(), error(), expect(), initParser(), and next().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/AST/BaseParser.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/AST/BaseParser.cpp