ArkScript: Ark::internal::ScopeResolver Class Reference
Ark::internal::ScopeResolver Class Reference
#include <NameResolutionPass.hpp>
Classes
class Scope
Public Member Functions
ScopeResolver ()
Create a ScopeResolver.
void createNew ()
Create a new scope.
void removeLocalScope ()
Remove the last scope.
void registerInCurrent (const std::string &name, bool is_mutable)
Register a variable in the current (last) scope.
std::optional< bool > isImmutable (const std::string &name) const
Checks the scopes in reverse order for 'name' and returns its mutability status.
bool isRegistered (const std::string &name) const
Checks if any scope has 'name', in reverse order.
bool isInScope (const std::string &name) const
Checks if 'name' is in the current scope.
Private Attributes
std::vector< Scope > m_scopes
Detailed Description
Definition at line 44 of file NameResolutionPass.hpp.
Constructor & Destructor Documentation
ScopeResolver()
Ark::internal::ScopeResolver::ScopeResolver ()
Create a ScopeResolver.
Kickstart by create a default global scope
Definition at line 29 of file NameResolutionPass.cpp.
References createNew().
Member Function Documentation
createNew()
void Ark::internal::ScopeResolver::createNew ()
Create a new scope.
Definition at line 34 of file NameResolutionPass.cpp.
References m_scopes.
Referenced by ScopeResolver(), and Ark::internal::NameResolutionPass::visitKeyword().
isImmutable()
std::optional< bool > Ark::internal::ScopeResolver::isImmutable (const std::string & name) const nodiscard
Checks the scopes in reverse order for 'name' and returns its mutability status.
Parameters
name
Returns
std::nullopt if the variable could not be found
true if immutable
false if mutable
Definition at line 49 of file NameResolutionPass.cpp.
References m_scopes.
Referenced by Ark::internal::NameResolutionPass::visit(), and Ark::internal::NameResolutionPass::visitKeyword().
isInScope()
bool Ark::internal::ScopeResolver::isInScope (const std::string & name) const nodiscard
Checks if 'name' is in the current scope.
Parameters
name
Returns
Definition at line 69 of file NameResolutionPass.cpp.
References m_scopes.
Referenced by Ark::internal::NameResolutionPass::visitKeyword().
isRegistered()
bool Ark::internal::ScopeResolver::isRegistered (const std::string & name) const nodiscard
Checks if any scope has 'name', in reverse order.
Parameters
name
Returns
Definition at line 59 of file NameResolutionPass.cpp.
References m_scopes.
Referenced by Ark::internal::NameResolutionPass::visitKeyword().
registerInCurrent()
void Ark::internal::ScopeResolver::registerInCurrent (const std::string & name, bool is_mutable)
Register a variable in the current (last) scope.
Parameters
name
is_mutable
Definition at line 44 of file NameResolutionPass.cpp.
References m_scopes.
Referenced by Ark::internal::NameResolutionPass::addDefinedSymbol().
removeLocalScope()
void Ark::internal::ScopeResolver::removeLocalScope ()
Remove the last scope.
Definition at line 39 of file NameResolutionPass.cpp.
References m_scopes.
Referenced by Ark::internal::NameResolutionPass::visitKeyword().
Member Data Documentation
m_scopes
std::vector<Scope> Ark::internal::ScopeResolver::m_scopes private
Definition at line 118 of file NameResolutionPass.hpp.
Referenced by createNew(), isImmutable(), isInScope(), isRegistered(), registerInCurrent(), and removeLocalScope().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/NameResolutionPass.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/NameResolutionPass.cpp