ArkScript: Ark::internal::Compiler Class Reference
Ark::internal::Compiler Class Reference final
The ArkScript bytecode compiler.
#include <Compiler.hpp>
Classes
struct Page
Public Member Functions
Compiler (unsigned debug)
Construct a new Compiler object.
void process (const Node &ast)
Start the compilation.
const std::vector< IR::Block > & intermediateRepresentation () const noexcept
Return the IR blocks (one per scope)
const std::vector< std::string > & symbols () const noexcept
Return the symbol table pre-computed.
const std::vector< ValTableElem > & values () const noexcept
Return the value table pre-computed.
Private Member Functions
IR::Block & page (const Page page) noexcept
helper functions to get a temp or finalized code page
void compileExpression (const Node &x, Page p, bool is_result_unused, bool is_terminal, const std::string &var_name="")
Compile an expression (a node) recursively.
void compileSymbol (const Node &x, Page p, bool is_result_unused)
void compileListInstruction (const Node &c0, const Node &x, Page p, bool is_result_unused)
void compileIf (const Node &x, Page p, bool is_result_unused, bool is_terminal, const std::string &var_name)
void compileFunction (const Node &x, Page p, bool is_result_unused, const std::string &var_name)
void compileLetMutSet (Keyword n, const Node &x, Page p)
void compileWhile (const Node &x, Page p)
void compilePluginImport (const Node &x, Page p)
void handleCalls (const Node &x, Page p, bool is_result_unused, bool is_terminal, const std::string &var_name)
uint16_t addSymbol (const Node &sym)
Register a given node in the symbol table.
uint16_t addValue (const Node &x)
Register a given node in the value table.
uint16_t addValue (std::size_t page_id, const Node &current)
Register a page id (function reference) in the value table.
Static Private Member Functions
static std::optional< Instruction > getOperator (const std::string &name) noexcept
Checking if a symbol is an operator.
static std::optional< uint16_t > getBuiltin (const std::string &name) noexcept
Checking if a symbol is a builtin.
static std::optional< Instruction > getListInstruction (const std::string &name) noexcept
Checking if a symbol is a list instruction.
static bool nodeProducesOutput (const Node &node)
static bool isUnaryInst (Instruction inst) noexcept
Check if a given instruction is unary (takes only one argument)
static void compilerWarning (const std::string &message, const Node &node)
Display a warning message.
static void throwCompilerError (const std::string &message, const Node &node)
Throw a nice error message.
Private Attributes
std::vector< std::string > m_symbols
std::vector< ValTableElem > m_values
std::vector< IR::Block > m_code_pages
std::vector< IR::Block > m_temp_pages
we need temporary code pages for some compilations passes
unsigned m_debug
the debug level of the compiler
Detailed Description
The ArkScript bytecode compiler.
Definition at line 35 of file Compiler.hpp.
Constructor & Destructor Documentation
Compiler()
Ark::internal::Compiler::Compiler (unsigned debug) explicit
Construct a new Compiler object.
Parameters
debug the debug level
Definition at line 21 of file Compiler.cpp.
Member Function Documentation
addSymbol()
uint16_t Ark::internal::Compiler::addSymbol (const Node & sym) private
Register a given node in the symbol table.
Can throw if the table is full
Parameters
sym
Returns
uint16_t
Definition at line 576 of file Compiler.cpp.
References m_symbols, Ark::internal::Node::string(), and throwCompilerError().
Referenced by compileExpression(), compileFunction(), compileLetMutSet(), and compileSymbol().
addValue() [1/2]
uint16_t Ark::internal::Compiler::addValue (const Node & x) private
Register a given node in the value table.
Can throw if the table is full
Parameters
x
Returns
uint16_t
Definition at line 592 of file Compiler.cpp.
References m_values, and throwCompilerError().
Referenced by compileExpression(), compileFunction(), and compilePluginImport().
addValue() [2/2]
uint16_t Ark::internal::Compiler::addValue (std::size_t page_id, const Node & current) private
Register a page id (function reference) in the value table.
Can throw if the table is full
Parameters
page_id
current A reference to the current node, for context
Returns
std::size_t
Definition at line 608 of file Compiler.cpp.
References m_values, and throwCompilerError().
compileExpression()
void Ark::internal::Compiler::compileExpression (const Node & x, Page p, bool is_result_unused, bool is_terminal, const std::string & var_name = "") private
Compile an expression (a node) recursively.
Parameters
x the Node to compile
p the current page number we're on
is_result_unused
is_terminal
var_name
Definition at line 118 of file Compiler.cpp.
References addSymbol(), addValue(), Ark::internal::Begin, Ark::internal::BUILTIN, compileExpression(), compileFunction(), compileIf(), compileLetMutSet(), compileListInstruction(), compilePluginImport(), compileSymbol(), compileWhile(), Ark::internal::Node::constList(), Ark::internal::DEL, Ark::internal::Del, Ark::internal::Field, Ark::internal::Fun, Ark::internal::GET_FIELD, getBuiltin(), getListInstruction(), handleCalls(), Ark::internal::If, Ark::internal::Import, Ark::internal::Keyword, Ark::internal::Let, Ark::internal::List, Ark::internal::LOAD_CONST, Ark::internal::Mut, Ark::internal::Node::nodeType(), Ark::internal::Number, page(), Ark::internal::Set, Ark::internal::String, Ark::internal::Symbol, throwCompilerError(), and Ark::internal::While.
Referenced by compileExpression(), compileFunction(), compileIf(), compileLetMutSet(), compileListInstruction(), compileWhile(), handleCalls(), and process().
compileFunction()
void Ark::internal::Compiler::compileFunction (const Node & x, Page p, bool is_result_unused, const std::string & var_name) private
Definition at line 305 of file Compiler.cpp.
References addSymbol(), addValue(), Ark::internal::CAPTURE, Ark::internal::Capture, compileExpression(), compilerWarning(), Ark::internal::Node::constList(), Ark::internal::List, Ark::internal::LOAD_CONST, m_code_pages, Ark::internal::MAKE_CLOSURE, page(), Ark::internal::POP, Ark::internal::RET, Ark::internal::STORE, Ark::internal::Symbol, throwCompilerError(), and Ark::internal::typeToString().
Referenced by compileExpression().
compileIf()
void Ark::internal::Compiler::compileIf (const Node & x, Page p, bool is_result_unused, bool is_terminal, const std::string & var_name) private
Definition at line 280 of file Compiler.cpp.
References compileExpression(), Ark::internal::Node::constList(), Ark::internal::IR::Entity::Goto(), Ark::internal::IR::Entity::GotoIf(), Ark::internal::IR::Entity::Label(), and page().
Referenced by compileExpression().
compileLetMutSet()
void Ark::internal::Compiler::compileLetMutSet (Keyword n, const Node & x, Page p) private
Definition at line 350 of file Compiler.cpp.
References addSymbol(), compileExpression(), Ark::internal::Node::constList(), Ark::internal::Let, Ark::internal::Mut, page(), Ark::internal::SET_VAL, Ark::internal::STORE, Ark::internal::Symbol, throwCompilerError(), and Ark::internal::typeToString().
Referenced by compileExpression().
compileListInstruction()
void Ark::internal::Compiler::compileListInstruction (const Node & c0, const Node & x, Page p, bool is_result_unused) private
Definition at line 229 of file Compiler.cpp.
References Ark::internal::APPEND, Ark::internal::APPEND_IN_PLACE, compileExpression(), compilerWarning(), Ark::internal::CONCAT, Ark::internal::CONCAT_IN_PLACE, Ark::internal::Node::constList(), getListInstruction(), Ark::internal::LIST, nodeProducesOutput(), page(), Ark::internal::POP, Ark::internal::Node::string(), and throwCompilerError().
Referenced by compileExpression().
compilePluginImport()
void Ark::internal::Compiler::compilePluginImport (const Node & x, Page p) private
Definition at line 394 of file Compiler.cpp.
References addValue(), Ark::internal::Node::constList(), page(), Ark::internal::PLUGIN, and Ark::internal::String.
Referenced by compileExpression().
compilerWarning()
void Ark::internal::Compiler::compilerWarning (const std::string & message, const Node & node) static private
Display a warning message.
Parameters
message
node
Definition at line 108 of file Compiler.cpp.
References Ark::Diagnostics::makeContextWithNode().
Referenced by compileFunction(), compileListInstruction(), and compileSymbol().
compileSymbol()
void Ark::internal::Compiler::compileSymbol (const Node & x, Page p, bool is_result_unused) private
Definition at line 211 of file Compiler.cpp.
References addSymbol(), Ark::internal::BUILTIN, compilerWarning(), getBuiltin(), getOperator(), Ark::internal::LOAD_SYMBOL, page(), Ark::internal::POP, Ark::internal::Node::string(), and throwCompilerError().
Referenced by compileExpression().
compileWhile()
void Ark::internal::Compiler::compileWhile (const Node & x, Page p) private
Definition at line 371 of file Compiler.cpp.
References compileExpression(), Ark::internal::Node::constList(), Ark::internal::IR::Entity::Goto(), Ark::internal::IR::Entity::GotoIf(), Ark::internal::IR::Entity::Label(), page(), and throwCompilerError().
Referenced by compileExpression().
getBuiltin()
std::optional< uint16_t > Ark::internal::Compiler::getBuiltin (const std::string & name) static private noexcept
Checking if a symbol is a builtin.
Parameters
name symbol name
Returns
std::optional<uint16_t> builtin number
Definition at line 60 of file Compiler.cpp.
References Ark::internal::Builtins::builtins.
Referenced by compileExpression(), and compileSymbol().
getListInstruction()
std::optional< Instruction > Ark::internal::Compiler::getListInstruction (const std::string & name) static private noexcept
Checking if a symbol is a list instruction.
Parameters
name
Returns
std::optional<Instruction> list instruction
Definition at line 71 of file Compiler.cpp.
References Ark::internal::LIST, and Ark::internal::Language::listInstructions.
Referenced by compileExpression(), and compileListInstruction().
getOperator()
std::optional< Instruction > Ark::internal::Compiler::getOperator (const std::string & name) static private noexcept
Checking if a symbol is an operator.
Parameters
name symbol name
Returns
std::optional<Instruction> operator instruction
Definition at line 52 of file Compiler.cpp.
References Ark::internal::FIRST_OPERATOR, and Ark::internal::Language::operators.
Referenced by compileSymbol(), and handleCalls().
handleCalls()
void Ark::internal::Compiler::handleCalls (const Node & x, Page p, bool is_result_unused, bool is_terminal, const std::string & var_name) private
Definition at line 412 of file Compiler.cpp.
References Ark::internal::ADD, Ark::internal::Language::And, Ark::internal::ASSERT, Ark::internal::CALL, Ark::internal::Capture, compileExpression(), Ark::internal::Node::constList(), Ark::internal::DIV, Ark::internal::DUP, Ark::internal::FIRST_OPERATOR, getOperator(), Ark::internal::IR::Entity::GotoIf(), isUnaryInst(), Ark::internal::JUMP, Ark::internal::IR::Entity::Label(), m_temp_pages, Ark::internal::MOD, Ark::internal::MUL, nodeProducesOutput(), Ark::internal::Language::operators, Ark::internal::Language::Or, page(), Ark::internal::POP, Ark::internal::SUB, Ark::internal::Symbol, and throwCompilerError().
Referenced by compileExpression().
intermediateRepresentation()
const std::vector< IR::Block > & Ark::internal::Compiler::intermediateRepresentation () const nodiscard noexcept
Return the IR blocks (one per scope)
Returns
const std::vector<Block>&
Definition at line 37 of file Compiler.cpp.
References m_code_pages.
Referenced by Ark::Welder::generateBytecode().
isUnaryInst()
bool Ark::internal::Compiler::isUnaryInst (Instruction inst) static private noexcept
Check if a given instruction is unary (takes only one argument)
Parameters
inst
Returns
true the instruction is unary
false
Definition at line 88 of file Compiler.cpp.
References Ark::internal::EMPTY, Ark::internal::HEAD, Ark::internal::ISNIL, Ark::internal::LEN, Ark::internal::NOT, Ark::internal::TAIL, Ark::internal::TO_NUM, Ark::internal::TO_STR, and Ark::internal::TYPE.
Referenced by handleCalls().
nodeProducesOutput()
bool Ark::internal::Compiler::nodeProducesOutput (const Node & node) static private
Checks if a node is a list and has a keyboard as its first node, indicating if it's producing a value on the stack or not
Parameters
node node to check
Returns
true if the node produces an output on the stack (fun, if, begin)
false otherwise (let, mut, set, while, import, del)
Definition at line 79 of file Compiler.cpp.
References Ark::internal::Begin, Ark::internal::Node::constList(), Ark::internal::Fun, Ark::internal::If, Ark::internal::Keyword, Ark::internal::List, and Ark::internal::Node::nodeType().
Referenced by compileListInstruction(), and handleCalls().
page()
IR::Block & Ark::internal::Compiler::page (const Page page) inline private noexcept
helper functions to get a temp or finalized code page
Parameters
page page descriptor
Returns
std::vector<IR::Block>&
Definition at line 94 of file Compiler.hpp.
Referenced by compileExpression(), compileFunction(), compileIf(), compileLetMutSet(), compileListInstruction(), compilePluginImport(), compileSymbol(), compileWhile(), and handleCalls().
process()
void Ark::internal::Compiler::process (const Node & ast)
Start the compilation.
Parameters
ast
Definition at line 25 of file Compiler.cpp.
References compileExpression(), and m_code_pages.
Referenced by Ark::Welder::generateBytecode().
symbols()
const std::vector< std::string > & Ark::internal::Compiler::symbols () const nodiscard noexcept
Return the symbol table pre-computed.
Returns
const std::vector<std::string>&
Definition at line 42 of file Compiler.cpp.
References m_symbols.
Referenced by Ark::Welder::generateBytecode().
throwCompilerError()
void Ark::internal::Compiler::throwCompilerError (const std::string & message, const Node & node) static private
Throw a nice error message.
Parameters
message
node
Definition at line 113 of file Compiler.cpp.
References Ark::internal::Node::col(), Ark::internal::Node::filename(), Ark::internal::Node::line(), and Ark::internal::Node::repr().
Referenced by addSymbol(), addValue(), addValue(), compileExpression(), compileFunction(), compileLetMutSet(), compileListInstruction(), compileSymbol(), compileWhile(), and handleCalls().
values()
const std::vector< ValTableElem > & Ark::internal::Compiler::values () const nodiscard noexcept
Return the value table pre-computed.
Returns
const std::vector<ValTableElem>&
Definition at line 47 of file Compiler.cpp.
References m_values.
Referenced by Ark::Welder::generateBytecode().
Member Data Documentation
m_code_pages
std::vector<IR::Block> Ark::internal::Compiler::m_code_pages private
Definition at line 83 of file Compiler.hpp.
Referenced by compileFunction(), intermediateRepresentation(), and process().
m_debug
unsigned Ark::internal::Compiler::m_debug private
the debug level of the compiler
Definition at line 86 of file Compiler.hpp.
m_symbols
std::vector<std::string> Ark::internal::Compiler::m_symbols private
Definition at line 81 of file Compiler.hpp.
Referenced by addSymbol(), and symbols().
m_temp_pages
std::vector<IR::Block> Ark::internal::Compiler::m_temp_pages private
we need temporary code pages for some compilations passes
Definition at line 84 of file Compiler.hpp.
Referenced by handleCalls().
m_values
std::vector<ValTableElem> Ark::internal::Compiler::m_values private
Definition at line 82 of file Compiler.hpp.
Referenced by addValue(), addValue(), and values().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/Compiler.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/Compiler.cpp