ArkScript: Ark::internal::MacroProcessor Class Reference
Ark::internal::MacroProcessor Class Reference final
The class handling the macros definitions and calls, given an AST.
#include <Processor.hpp>
Public Member Functions
MacroProcessor (unsigned debug) noexcept
Construct a new Macro Processor object.
void process (const Node &ast) override
Send the complete AST and work on it.
const Node & ast () const noexcept override
Return the modified AST.
Public Member Functions inherited from Ark::internal::Pass
Pass (std::string name, unsigned debug_level)
Construct a new Pass object.
virtual ~Pass ()=default
Private Member Functions
const Node * findNearestMacro (const std::string &name) const
Find the nearest macro matching a given name.
void deleteNearestMacro (const std::string &name)
Find the nearest macro matching a given name and delete it.
bool isPredefined (const std::string &symbol)
Check if a given symbol is a predefined macro or not.
void recurApply (Node &node)
Recursively apply macros on a given node.
bool isConstEval (const Node &node) const
Check if a node can be evaluated at compile time.
void registerMacro (Node &node)
Registers macros based on their type.
void registerFuncDef (const Node &node)
Registers a function definition node.
void processNode (Node &node, unsigned depth)
Register macros in scopes and apply them as needed.
bool applyMacro (Node &node, unsigned depth) const
Apply a macro on a given node.
void unify (const std::unordered_map< std::string, Node > &map, Node &target, Node *parent, std::size_t index, std::size_t unify_depth=0)
Unify a target node with a given map symbol => replacement node, recursively.
void setWithFileAttributes (const Node origin, Node &output, const Node &macro)
Set the file attributes of the output node based on the original node.
void checkMacroArgCount (const Node &node, std::size_t expected, const std::string &name, const std::string &kind="")
Check if the given node has exactly the provided argument count, otherwise throws an error.
Node evaluate (Node &node, unsigned depth, bool is_not_body=false)
Evaluate only the macros.
Static Private Member Functions
static bool hadBegin (const Node &node)
Check if a given node is a list node, and starts with a Begin.
static void removeBegin (Node &node, std::size_t i)
Remove a begin block added by a macro.
static bool isTruthy (const Node &node)
Check if a node can be evaluated to true.
static void throwMacroProcessingError (const std::string &message, const Node &node)
Throw a macro processing error.
Private Attributes
Node m_ast
The modified AST.
std::vector< MacroScope > m_macros
Handling macros in a scope fashion.
std::vector< std::shared_ptr< MacroExecutor > > m_executors
std::unordered_map< std::string, Node > m_defined_functions
Friends
class MacroExecutor
Additional Inherited Members
Protected Attributes inherited from Ark::internal::Pass
Logger m_logger
Detailed Description
The class handling the macros definitions and calls, given an AST.
Definition at line 31 of file Processor.hpp.
Constructor & Destructor Documentation
MacroProcessor()
Ark::internal::MacroProcessor::MacroProcessor (unsigned debug) explicit noexcept
Construct a new Macro Processor object.
Parameters
debug the debug level
Definition at line 19 of file Processor.cpp.
Member Function Documentation
applyMacro()
bool Ark::internal::MacroProcessor::applyMacro (Node & node, unsigned depth) const private
Apply a macro on a given node.
Parameters
node
depth
Returns
true if a macro was applied
false
Definition at line 189 of file Processor.cpp.
References m_executors, Ark::MaxMacroProcessingDepth, and throwMacroProcessingError().
Referenced by Ark::internal::MacroExecutor::applyMacroProxy(), evaluate(), processNode(), and recurApply().
ast()
const Node & Ark::internal::MacroProcessor::ast () const nodiscard override virtual noexcept
Return the modified AST.
Returns
Node&
Implements Ark::internal::Pass.
Definition at line 41 of file Processor.cpp.
References m_ast.
Referenced by Ark::Welder::computeAST(), evaluate(), and process().
checkMacroArgCount()
void Ark::internal::MacroProcessor::checkMacroArgCount (const Node & node, std::size_t expected, const std::string & name, const std::string & kind = "") private
Check if the given node has exactly the provided argument count, otherwise throws an error.
Parameters
node a list node with a macro application, eg (= a b)
expected expected argument count, not counting the macro
name the name of the macro being applied
kind the macro kind, empty by default (eg "operator", "condition")
Definition at line 252 of file Processor.cpp.
References Ark::internal::Node::constList(), and throwMacroProcessingError().
Referenced by evaluate().
deleteNearestMacro()
void Ark::internal::MacroProcessor::deleteNearestMacro (const std::string & name) private
Find the nearest macro matching a given name and delete it.
Parameters
name
Definition at line 605 of file Processor.cpp.
References m_macros.
Referenced by registerMacro().
evaluate()
Node Ark::internal::MacroProcessor::evaluate (Node & node, unsigned depth, bool is_not_body = false) private
Evaluate only the macros.
Parameters
node
depth
is_not_body true if the method is run on a non-body code (eg a condition of an if-macro)
Returns
Node
Definition at line 266 of file Processor.cpp.
References Ark::internal::Language::And, applyMacro(), Ark::internal::Language::Argcount, ast(), checkMacroArgCount(), Ark::internal::Node::col(), Ark::internal::Node::constList(), evaluate(), Ark::internal::Node::filename(), findNearestMacro(), Ark::internal::Fun, Ark::internal::getFalseNode(), Ark::internal::getListNode(), Ark::internal::getNilNode(), Ark::internal::getTrueNode(), isConstEval(), isTruthy(), Ark::internal::Keyword, Ark::internal::Node::line(), Ark::internal::List, Ark::internal::Node::list(), m_defined_functions, Ark::internal::Node::nodeType(), Ark::internal::Number, Ark::internal::Node::number(), Ark::internal::Language::Or, Ark::internal::Language::Paste, Ark::internal::Node::push_back(), Ark::internal::Language::Repr, Ark::internal::Node::repr(), Ark::internal::Node::setFilename(), Ark::internal::Node::setNodeType(), Ark::internal::Node::setPos(), Ark::internal::Node::setString(), setWithFileAttributes(), Ark::internal::Spread, Ark::internal::String, Ark::internal::Node::string(), Ark::internal::Symbol, Ark::internal::Language::Symcat, throwMacroProcessingError(), Ark::internal::typeToString(), and Ark::internal::Unused.
Referenced by evaluate().
findNearestMacro()
const Node * Ark::internal::MacroProcessor::findNearestMacro (const std::string & name) const nodiscard private
Find the nearest macro matching a given name.
Parameters
name
Returns
const Node* nullptr if no macro was found
Definition at line 592 of file Processor.cpp.
References m_macros.
Referenced by evaluate(), Ark::internal::MacroExecutor::findNearestMacro(), and isConstEval().
hadBegin()
bool Ark::internal::MacroProcessor::hadBegin (const Node & node) static private
Check if a given node is a list node, and starts with a Begin.
Parameters
node
Returns
true if it starts with a Begin
false
Definition at line 635 of file Processor.cpp.
References Ark::internal::Begin, Ark::internal::Node::constList(), Ark::internal::Keyword, Ark::internal::List, and Ark::internal::Node::nodeType().
Referenced by processNode().
isConstEval()
bool Ark::internal::MacroProcessor::isConstEval (const Node & node) const nodiscard private
Check if a node can be evaluated at compile time.
Parameters
node
Returns
true
false
Definition at line 664 of file Processor.cpp.
References Ark::internal::Builtins::builtins, Ark::internal::Capture, Ark::internal::Node::constList(), Ark::internal::Field, findNearestMacro(), Ark::internal::Keyword, Ark::internal::List, Ark::internal::Macro, Ark::internal::Node::nodeType(), Ark::internal::Number, Ark::internal::Language::operators, Ark::internal::Spread, Ark::internal::String, Ark::internal::Node::string(), Ark::internal::Symbol, and Ark::internal::Unused.
Referenced by evaluate().
isPredefined()
bool Ark::internal::MacroProcessor::isPredefined (const std::string & symbol) private
Check if a given symbol is a predefined macro or not.
Parameters
symbol
Returns
true
false
Definition at line 620 of file Processor.cpp.
References Ark::internal::Language::macros.
Referenced by Ark::internal::MacroExecutor::isPredefined().
isTruthy()
bool Ark::internal::MacroProcessor::isTruthy (const Node & node) static private
Check if a node can be evaluated to true.
Parameters
node
Returns
true
false
Definition at line 576 of file Processor.cpp.
References Ark::internal::Node::nodeType(), Ark::internal::Number, Ark::internal::Node::number(), Ark::internal::Spread, Ark::internal::String, Ark::internal::Node::string(), Ark::internal::Symbol, and throwMacroProcessingError().
Referenced by evaluate(), and Ark::internal::MacroExecutor::isTruthy().
process()
void Ark::internal::MacroProcessor::process (const Node & ast) override virtual
Send the complete AST and work on it.
Parameters
ast
Implements Ark::internal::Pass.
Definition at line 28 of file Processor.cpp.
References ast(), Ark::internal::Logger::debug(), Ark::internal::Node::debugPrint(), m_ast, Ark::internal::Pass::m_logger, processNode(), Ark::internal::Logger::shouldTrace(), and Ark::internal::Logger::trace().
Referenced by Ark::Welder::computeAST().
processNode()
void Ark::internal::MacroProcessor::processNode (Node & node, unsigned depth) private
Register macros in scopes and apply them as needed.
Parameters
node node on which to operate
depth
Definition at line 117 of file Processor.cpp.
References applyMacro(), Ark::internal::Node::constList(), hadBegin(), Ark::internal::List, Ark::internal::Node::list(), m_macros, Ark::internal::Macro, Ark::MaxMacroProcessingDepth, Ark::internal::Node::nodeType(), processNode(), recurApply(), registerFuncDef(), registerMacro(), removeBegin(), throwMacroProcessingError(), and Ark::internal::Unused.
Referenced by process(), and processNode().
recurApply()
void Ark::internal::MacroProcessor::recurApply (Node & node) private
Recursively apply macros on a given node.
Parameters
node
Definition at line 626 of file Processor.cpp.
References applyMacro(), Ark::internal::Node::isListLike(), Ark::internal::Node::list(), and recurApply().
Referenced by processNode(), and recurApply().
registerFuncDef()
void Ark::internal::MacroProcessor::registerFuncDef (const Node & node) private
Registers a function definition node.
Parameters
node
Definition at line 93 of file Processor.cpp.
References Ark::internal::Node::constList(), Ark::internal::Fun, Ark::internal::Keyword, Ark::internal::Let, Ark::internal::List, m_defined_functions, Ark::internal::Mut, Ark::internal::Node::nodeType(), Ark::internal::Set, Ark::internal::Node::string(), Ark::internal::Symbol, throwMacroProcessingError(), and Ark::internal::typeToString().
Referenced by processNode().
registerMacro()
void Ark::internal::MacroProcessor::registerMacro (Node & node) private
Registers macros based on their type.
Validate macros and register them by their name
Parameters
node A node of type Macro
Definition at line 46 of file Processor.cpp.
References Ark::internal::Node::constList(), deleteNearestMacro(), Ark::internal::List, Ark::internal::Node::list(), m_macros, Ark::internal::Node::nodeType(), Ark::internal::Spread, Ark::internal::Node::string(), Ark::internal::Symbol, and throwMacroProcessingError().
Referenced by processNode(), and Ark::internal::MacroExecutor::registerMacro().
removeBegin()
void Ark::internal::MacroProcessor::removeBegin (Node & node, std::size_t i) static private
Remove a begin block added by a macro.
Parameters
node
i
Definition at line 643 of file Processor.cpp.
References Ark::internal::Begin, Ark::internal::Node::constList(), Ark::internal::Node::isListLike(), Ark::internal::Keyword, Ark::internal::Node::keyword(), Ark::internal::List, Ark::internal::Node::list(), and Ark::internal::Node::nodeType().
Referenced by processNode().
setWithFileAttributes()
void Ark::internal::MacroProcessor::setWithFileAttributes (const Node origin, Node & output, const Node & macro) private
Set the file attributes of the output node based on the original node.
Parameters
origin original node
output output node which will be modified
macro modified node, macro applied
Definition at line 245 of file Processor.cpp.
References Ark::internal::Node::col(), Ark::internal::Node::filename(), Ark::internal::Node::line(), Ark::internal::Node::setFilename(), and Ark::internal::Node::setPos().
Referenced by evaluate().
throwMacroProcessingError()
void Ark::internal::MacroProcessor::throwMacroProcessingError (const std::string & message, const Node & node) static private
Throw a macro processing error.
Parameters
message the error
node the node in which there is an error
Definition at line 703 of file Processor.cpp.
References Ark::internal::Node::col(), Ark::internal::Node::filename(), Ark::internal::Node::line(), and Ark::internal::Node::repr().
Referenced by applyMacro(), checkMacroArgCount(), evaluate(), isTruthy(), processNode(), registerFuncDef(), registerMacro(), Ark::internal::MacroExecutor::throwMacroProcessingError(), and unify().
unify()
void Ark::internal::MacroProcessor::unify (const std::unordered_map< std::string, Node > & map, Node & target, Node * parent, std::size_t index, std::size_t unify_depth = 0) private
Unify a target node with a given map symbol => replacement node, recursively.
Parameters
map
target
parent
index position of target inside parent->list()
unify_depth call depth to unify, to avoid deep recursive unification
Definition at line 209 of file Processor.cpp.
References Ark::internal::Node::isListLike(), Ark::internal::List, Ark::internal::Node::list(), Ark::MaxMacroUnificationDepth, Ark::internal::Node::nodeType(), Ark::internal::Node::setNodeType(), Ark::internal::Spread, Ark::internal::Node::string(), Ark::internal::Symbol, throwMacroProcessingError(), Ark::internal::typeToString(), and unify().
Referenced by Ark::internal::MacroExecutor::unify(), and unify().
Friends And Related Symbol Documentation
MacroExecutor
friend class MacroExecutor friend
Definition at line 55 of file Processor.hpp.
Member Data Documentation
m_ast
Node Ark::internal::MacroProcessor::m_ast private
The modified AST.
Definition at line 58 of file Processor.hpp.
Referenced by ast(), and process().
m_defined_functions
std::unordered_map<std::string, Node> Ark::internal::MacroProcessor::m_defined_functions private
Definition at line 61 of file Processor.hpp.
Referenced by evaluate(), and registerFuncDef().
m_executors
std::vector<std::shared_ptr<MacroExecutor> > Ark::internal::MacroProcessor::m_executors private
Definition at line 60 of file Processor.hpp.
Referenced by applyMacro().
m_macros
std::vector<MacroScope> Ark::internal::MacroProcessor::m_macros private
Handling macros in a scope fashion.
Definition at line 59 of file Processor.hpp.
Referenced by deleteNearestMacro(), findNearestMacro(), processNode(), and registerMacro().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/Macros/Processor.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/Macros/Processor.cpp