ArkScript: json Namespace Reference
json Namespace Reference
Functions
std::vector< std::unique_ptr< nlohmann::json > > & get_json_object ()
UserType::ControlFuncs * get_cfs ()
Value open (std::vector< Value > &args, Ark::VM *vm)
Value fromString (std::vector< Value > &args, Ark::VM *vm)
Value jsonToArk (nlohmann::json &obj)
Value get (std::vector< Value > &args, Ark::VM *vm)
Value toString (std::vector< Value > &args, Ark::VM *vm)
nlohmann::json listToJson (std::vector< Value > &arkList)
Value jset (std::vector< Value > &args, Ark::VM *vm)
Value write (std::vector< Value > &args, Ark::VM *vm)
Value fromList (std::vector< Value > &args, Ark::VM *vm)
Value len (std::vector< Value > &args, Ark::VM *vm)
Function Documentation
fromList()
Value json::fromList (std::vector< Value > & args, Ark::VM * vm)
Definition at line 263 of file main.cpp.
References Ark::types::check(), Ark::False, Ark::types::generateError(), get_cfs(), get_json_object(), listToJson(), toString(), and Ark::True.
Referenced by getFunctionsMapping().
fromString()
Value json::fromString (std::vector< Value > & args, Ark::VM * vm)
Definition at line 53 of file main.cpp.
References Ark::types::check(), Ark::types::generateError(), get_cfs(), and get_json_object().
Referenced by getFunctionsMapping().
get()
Value json::get (std::vector< Value > & args, Ark::VM * vm)
Definition at line 96 of file main.cpp.
References Ark::UserType::as(), Ark::types::check(), Ark::types::generateError(), jsonToArk(), Ark::Nil, and Ark::Value::usertypeRef().
Referenced by getFunctionsMapping(), msgpack_obj_handle(), and msgpack_sbuffer().
get_cfs()
UserType::ControlFuncs * json::get_cfs ()
Definition at line 15 of file main.cpp.
References Ark::UserType::ControlFuncs::deleter, get_json_object(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by fromList(), fromString(), jsonToArk(), and open().
get_json_object()
std::vector< std::unique_ptr< nlohmann::json > > & json::get_json_object ()
Definition at line 9 of file main.cpp.
Referenced by fromList(), fromString(), get_cfs(), jsonToArk(), and open().
jset()
Value json::jset (std::vector< Value > & args, Ark::VM * vm)
Definition at line 189 of file main.cpp.
References Ark::types::check(), Ark::False, Ark::types::generateError(), listToJson(), Ark::Nil, and Ark::True.
Referenced by getFunctionsMapping().
jsonToArk()
Value json::jsonToArk (nlohmann::json & obj)
Definition at line 71 of file main.cpp.
References Ark::False, get_cfs(), get_json_object(), jsonToArk(), Ark::Nil, Ark::Value::push_back(), and Ark::True.
Referenced by get(), and jsonToArk().
len()
Value json::len (std::vector< Value > & args, Ark::VM * vm)
Definition at line 317 of file main.cpp.
References Ark::types::check(), and Ark::types::generateError().
Referenced by getFunctionsMapping(), hook_color(), mapping_create(), md5::md5(), and md5::md5bin().
listToJson()
nlohmann::json json::listToJson (std::vector< Value > & arkList)
Definition at line 148 of file main.cpp.
References Ark::UserType::as(), Ark::False, listToJson(), Ark::True, and Ark::Value::usertypeRef().
Referenced by fromList(), jset(), and listToJson().
open()
Value json::open (std::vector< Value > & args, Ark::VM * vm)
Definition at line 33 of file main.cpp.
References Ark::types::check(), Ark::types::generateError(), get_cfs(), and get_json_object().
Referenced by getFunctionsMapping().
toString()
Value json::toString (std::vector< Value > & args, Ark::VM * vm)
Definition at line 136 of file main.cpp.
References Ark::types::check(), and Ark::types::generateError().
Referenced by fromList(), getFunctionsMapping(), http_create_client(), and ArkHash::md5().
write()
Value json::write (std::vector< Value > & args, Ark::VM * vm)
Definition at line 246 of file main.cpp.
References Ark::types::check(), Ark::types::generateError(), and Ark::Nil.
Referenced by getFunctionsMapping().