ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/msgpack/include/objects.hpp File Reference
objects.hpp File Reference
#include <variant>
#include <memory>
#include <msgpack.hpp>
#include <Ark/Module.hpp>
Typedefs
using CObject = std::variant< bool, double, std::string, std::vector< Value > >
Functions
std::list< std::unique_ptr< msgpack::sbuffer > > & get_sbuffers ()
std::list< std::unique_ptr< msgpack::object_handle > > & get_obj_handlers ()
std::list< std::unique_ptr< msgpack::object > > & get_objects ()
UserType::ControlFuncs * get_cfs_sbuffers ()
UserType::ControlFuncs * get_cfs_obj_handlers ()
UserType::ControlFuncs * get_cfs_objects ()
CObject get_cobject (Value &ark_object, ValueType type)
Value msgpack_obj_handle (std::vector< Value > &args, VM *vm)
Value msgpack_sbuffer (std::vector< Value > &args, VM *vm)
Value msgpack_obj (std::vector< Value > &args, VM *vm)
Typedef Documentation
CObject
using CObject = std::variant<bool, double, std::string, std::vector<Value> >
Definition at line 11 of file objects.hpp.
Function Documentation
get_cfs_obj_handlers()
UserType::ControlFuncs * get_cfs_obj_handlers ()
Definition at line 45 of file objects.cpp.
References Ark::UserType::ControlFuncs::deleter, get_obj_handlers(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by msgpack_obj_handle().
get_cfs_objects()
UserType::ControlFuncs * get_cfs_objects ()
Definition at line 68 of file objects.cpp.
References Ark::UserType::ControlFuncs::deleter, get_objects(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by msgpack_obj().
get_cfs_sbuffers()
UserType::ControlFuncs * get_cfs_sbuffers ()
Definition at line 22 of file objects.cpp.
References Ark::UserType::ControlFuncs::deleter, get_sbuffers(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by msgpack_sbuffer().
get_cobject()
CObject get_cobject (Value & ark_object, ValueType type)
Definition at line 91 of file objects.cpp.
References Ark::False, Ark::Value::list(), Ark::Nil, Ark::Value::number(), Ark::Value::stringRef(), and Ark::True.
get_obj_handlers()
std::list< std::unique_ptr< msgpack::object_handle > > & get_obj_handlers ()
Definition at line 10 of file objects.cpp.
Referenced by get_cfs_obj_handlers(), and msgpack_obj_handle().
get_objects()
std::list< std::unique_ptr< msgpack::object > > & get_objects ()
Definition at line 16 of file objects.cpp.
Referenced by get_cfs_objects(), and msgpack_obj().
get_sbuffers()
std::list< std::unique_ptr< msgpack::sbuffer > > & get_sbuffers ()
Definition at line 4 of file objects.cpp.
Referenced by get_cfs_sbuffers(), and msgpack_sbuffer().
msgpack_obj()
Value msgpack_obj (std::vector< Value > & args, VM * vm)
Definition at line 140 of file objects.cpp.
References Ark::types::check(), Ark::types::generateError(), get_cfs_objects(), and get_objects().
Referenced by getFunctionsMapping().
msgpack_obj_handle()
Value msgpack_obj_handle (std::vector< Value > & args, VM * vm)
Definition at line 135 of file objects.cpp.
References json::get(), get_cfs_obj_handlers(), and get_obj_handlers().
Referenced by getFunctionsMapping().
msgpack_sbuffer()
Value msgpack_sbuffer (std::vector< Value > & args, VM * vm)
Definition at line 130 of file objects.cpp.
References json::get(), get_cfs_sbuffers(), and get_sbuffers().
Referenced by getFunctionsMapping().