ArkScript: C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/lib/modules/http/src/utils.cpp File Reference
utils.cpp File Reference
#include <httplib.h>
#include <http_module.hpp>
#include <algorithm>
#include <list>
#include <ctime>
Functions
std::list< Params > & get_params ()
std::list< Headers > & get_headers ()
std::list< Client > & get_clients ()
int & get_logger_level ()
bool & get_error_handler ()
Server & create_server ()
UserType::ControlFuncs * get_cfs_client ()
UserType::ControlFuncs * get_cfs_header ()
UserType::ControlFuncs * get_cfs_param ()
void typecheck (std::string_view funcname, const std::vector< Value > &n)
Function Documentation
create_server()
Server & create_server ()
Definition at line 41 of file utils.cpp.
References get_error_handler(), and get_logger_level().
Referenced by handle_request_for(), http_create_server(), http_server_listen(), http_server_remove_mount_point(), http_server_set_fext_mimetype(), http_server_set_mount_point(), and http_server_stop().
get_cfs_client()
UserType::ControlFuncs * get_cfs_client ()
Definition at line 78 of file utils.cpp.
References Ark::UserType::ControlFuncs::deleter, get_clients(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by http_create_client().
get_cfs_header()
UserType::ControlFuncs * get_cfs_header ()
Definition at line 99 of file utils.cpp.
References Ark::UserType::ControlFuncs::deleter, get_headers(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by http_create_headers().
get_cfs_param()
UserType::ControlFuncs * get_cfs_param ()
Definition at line 123 of file utils.cpp.
References Ark::UserType::ControlFuncs::deleter, get_params(), and Ark::UserType::ControlFuncs::ostream_func.
Referenced by handle_request_for(), and http_create_params().
get_clients()
std::list< Client > & get_clients ()
Definition at line 23 of file utils.cpp.
Referenced by get_cfs_client(), and http_create_client().
get_error_handler()
bool & get_error_handler ()
Definition at line 35 of file utils.cpp.
Referenced by create_server().
get_headers()
std::list< Headers > & get_headers ()
Definition at line 17 of file utils.cpp.
Referenced by get_cfs_header(), and http_create_headers().
get_logger_level()
int & get_logger_level ()
Definition at line 29 of file utils.cpp.
Referenced by create_server(), and http_server_enable_logger().
get_params()
std::list< Params > & get_params ()
Definition at line 11 of file utils.cpp.
Referenced by get_cfs_param(), handle_request_for(), and http_create_params().
typecheck()
void typecheck (std::string_view funcname, const std::vector< Value > & n)
Definition at line 147 of file utils.cpp.
References Ark::types::generateError().
Referenced by handle_request_for().