ArkScript: Ark::internal::SymbolExecutor Class Reference
Ark::internal::SymbolExecutor Class Reference
Handles Symbol macros.
#include <Symbol.hpp>
Public Member Functions
bool applyMacro (Node &node) override
Executes macros in the Node if the Executor can handle it.
bool canHandle (Node &node) override
Checks if the executor can apply a macro on the passed Node.
MacroExecutor (MacroProcessor *macroprocessor, unsigned debug=0)
Construct a new Macro Executor object.
Public Member Functions inherited from Ark::internal::MacroExecutor
MacroExecutor (MacroProcessor *macroprocessor, unsigned debug=0)
Construct a new Macro Executor object.
virtual ~MacroExecutor ()
Need a virtual destructor to correctly destory object.
Additional Inherited Members
Protected Member Functions inherited from Ark::internal::MacroExecutor
Node * findNearestMacro (const std::string &name)
Find the nearest macro matching a giving name.
void registerMacro (Node &node)
Registers macros based on their type.
bool isTruthy (const Node &node)
Check if a node can be evaluated to true.
Node evaluate (Node &node, bool is_not_body)
Evaluate only the macros.
void unify (const std::unordered_map< std::string, Node > &, Node &, Node *)
Applies the spread operator.
void throwMacroProcessingError (const std::string &message, const Node &node)
Throw a macro processing error.
bool applyMacroProxy (Node &node)
Execute a node, trying to emplace macros calls.
bool isPredefined (const std::string &symbol)
Check if a given symbol is a predefined macro.
Protected Attributes inherited from Ark::internal::MacroExecutor
unsigned int m_debug
MacroProcessor * m_macroprocessor
Detailed Description
Handles Symbol macros.
Definition at line 24 of file Symbol.hpp.
Member Function Documentation
applyMacro()
bool Ark::internal::SymbolExecutor::applyMacro (Node & node) override virtual
Executes macros in the Node if the Executor can handle it.
Parameters
node the node that contains a macro
Returns
true if a macro was successfully applied
false
Implements Ark::internal::MacroExecutor.
Definition at line 10 of file Symbol.cpp.
References Ark::internal::Node::constList(), Ark::internal::MacroExecutor::findNearestMacro(), Ark::internal::Node::list(), and Ark::internal::Node::string().
canHandle()
bool Ark::internal::SymbolExecutor::canHandle (Node & node) override virtual
Checks if the executor can apply a macro on the passed Node.
Parameters
node the node that contains a macro
Implements Ark::internal::MacroExecutor.
Definition at line 5 of file Symbol.cpp.
References Ark::internal::Node::nodeType(), and Ark::internal::Symbol.
MacroExecutor()
Ark::internal::MacroExecutor::MacroExecutor (MacroProcessor * macroprocessor, unsigned debug = 0)
Construct a new Macro Executor object.
Parameters
macroprocessor
debug
Definition at line 36 of file Executor.cpp.
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/include/Ark/Compiler/Macros/Executors/Symbol.hpp
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/src/arkreactor/Compiler/Macros/Executors/Symbol.cpp