ArkScript: ArkBitwise Namespace Reference
ArkBitwise Namespace Reference
Functions
Value rshift (std::vector< Value > &n, Ark::VM *vm)
Value lshift (std::vector< Value > &n, Ark::VM *vm)
Value xor_ (std::vector< Value > &n, Ark::VM *vm)
Value or_ (std::vector< Value > &n, Ark::VM *vm)
Value and_ (std::vector< Value > &n, Ark::VM *vm)
Function Documentation
and_()
Value ArkBitwise::and_ (std::vector< Value > & n, Ark::VM * vm)
Definition at line 62 of file main.cpp.
References Ark::types::check(), and Ark::types::generateError().
Referenced by getFunctionsMapping().
lshift()
Value ArkBitwise::lshift (std::vector< Value > & n, Ark::VM * vm)
Definition at line 20 of file main.cpp.
References Ark::types::check(), and Ark::types::generateError().
Referenced by getFunctionsMapping().
or_()
Value ArkBitwise::or_ (std::vector< Value > & n, Ark::VM * vm)
Definition at line 48 of file main.cpp.
References Ark::types::check(), and Ark::types::generateError().
Referenced by getFunctionsMapping().
rshift()
Value ArkBitwise::rshift (std::vector< Value > & n, Ark::VM * vm)
Definition at line 6 of file main.cpp.
References Ark::types::check(), and Ark::types::generateError().
Referenced by getFunctionsMapping().
xor_()
Value ArkBitwise::xor_ (std::vector< Value > & n, Ark::VM * vm)
Definition at line 34 of file main.cpp.
References Ark::types::check(), and Ark::types::generateError().
Referenced by getFunctionsMapping().