ArkScript: Ark::BetterTypeError Class Reference
Ark::BetterTypeError Class Reference
A type error triggered when types don't match.
#include <Exceptions.hpp>
Public Member Functions
BetterTypeError (std::string_view func_name, std::size_t expected_argc, const std::vector< Value > &args)
BetterTypeError & withArg (std::string_view arg_name, ValueType arg_type)
BetterTypeError & withArg (std::string_view arg_name, const std::vector< ValueType > &arg_type)
Public Member Functions inherited from Ark::Error
Error (const std::string &message="")
Protected Attributes
std::string_view m_funcname
std::size_t m_arg_index
std::size_t m_expected_argc
std::vector< Value > m_args
Detailed Description
A type error triggered when types don't match.
Definition at line 36 of file Exceptions.hpp.
Constructor & Destructor Documentation
BetterTypeError()
Ark::BetterTypeError::BetterTypeError (std::string_view func_name, std::size_t expected_argc, const std::vector< Value > & args)
Definition at line 10 of file Exceptions.cpp.
Member Function Documentation
withArg() [1/2]
BetterTypeError & Ark::BetterTypeError::withArg (std::string_view arg_name, const std::vector< ValueType > & arg_type)
Definition at line 16 of file Exceptions.cpp.
References m_arg_index, m_args, and Ark::types_to_str.
withArg() [2/2]
BetterTypeError & Ark::BetterTypeError::withArg (std::string_view arg_name, ValueType arg_type)
Definition at line 58 of file Exceptions.cpp.
References withArg().
Referenced by Ark::VM::safeRun(), and withArg().
Member Data Documentation
m_arg_index
std::size_t Ark::BetterTypeError::m_arg_index protected
Definition at line 46 of file Exceptions.hpp.
Referenced by withArg().
m_args
std::vector<Value> Ark::BetterTypeError::m_args protected
Definition at line 48 of file Exceptions.hpp.
Referenced by withArg().
m_expected_argc
std::size_t Ark::BetterTypeError::m_expected_argc protected
Definition at line 47 of file Exceptions.hpp.
m_funcname
std::string_view Ark::BetterTypeError::m_funcname protected
Definition at line 45 of file Exceptions.hpp.
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/include/Ark/Exceptions.hpp
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/src/arkreactor/Exceptions.cpp