ArkScript: md5 Namespace Reference
md5 Namespace Reference
Classes
struct MD5_CTX
Typedefs
typedef unsigned int MD5_u32
Functions
std::string md5 (const std::string &dat)
std::string md5 (const void *dat, size_t len)
static void MD5_Init (MD5_CTX *ctx)
static void MD5_Update (MD5_CTX *ctx, const void *data, unsigned long size)
static void MD5_Final (unsigned char *result, MD5_CTX *ctx)
static const void * body (MD5_CTX *ctx, const void *data, unsigned long size)
void md5bin (const void *dat, std::size_t len, unsigned char out[16])
static char hb2hex (unsigned char hb)
std::string md5 (const void *dat, std::size_t len)
Typedef Documentation
MD5_u32
typedef unsigned int md5::MD5_u32
Definition at line 32 of file md5.cpp.
Function Documentation
body()
static const void * md5::body (MD5_CTX * ctx, const void * data, unsigned long size) static
Definition at line 46 of file md5.cpp.
References md5::MD5_CTX::a, md5::MD5_CTX::b, md5::MD5_CTX::c, md5::MD5_CTX::d, F, G, GET, H, I, SET, and STEP.
Referenced by MD5_Final(), and MD5_Update().
hb2hex()
static char md5::hb2hex (unsigned char hb) static
Definition at line 251 of file md5.cpp.
Referenced by md5().
md5() [1/3]
std::string md5::md5 (const std::string & dat)
Definition at line 270 of file md5.cpp.
References md5().
Referenced by md5(), and ArkHash::md5().
md5() [2/3]
std::string md5::md5 (const void * dat, size_t len)
md5() [3/3]
std::string md5::md5 (const void * dat, std::size_t len)
Definition at line 257 of file md5.cpp.
References hb2hex(), json::len(), and md5bin().
MD5_Final()
void md5::MD5_Final (unsigned char * result, MD5_CTX * ctx) static
Definition at line 193 of file md5.cpp.
References md5::MD5_CTX::a, md5::MD5_CTX::b, body(), md5::MD5_CTX::buffer, md5::MD5_CTX::c, md5::MD5_CTX::d, md5::MD5_CTX::hi, and md5::MD5_CTX::lo.
Referenced by md5bin().
MD5_Init()
void md5::MD5_Init (MD5_CTX * ctx) static
Definition at line 147 of file md5.cpp.
References md5::MD5_CTX::a, md5::MD5_CTX::b, md5::MD5_CTX::c, md5::MD5_CTX::d, md5::MD5_CTX::hi, and md5::MD5_CTX::lo.
Referenced by md5bin().
MD5_Update()
void md5::MD5_Update (MD5_CTX * ctx, const void * data, unsigned long size) static
Definition at line 158 of file md5.cpp.
References body(), md5::MD5_CTX::buffer, md5::MD5_CTX::hi, and md5::MD5_CTX::lo.
Referenced by md5bin().
md5bin()
void md5::md5bin (const void * dat, std::size_t len, unsigned char out[16])
Definition at line 243 of file md5.cpp.
References json::len(), MD5_Final(), MD5_Init(), and MD5_Update().
Referenced by md5().