ArkScript: Ark::internal::IR::Entity Class Reference
Ark::internal::IR::Entity Class Reference
#include <Entity.hpp>
Public Member Functions
Entity (Kind kind)
Entity (Instruction inst, uint16_t arg=0)
Entity (Instruction inst, uint16_t primary_arg, uint16_t secondary_arg)
Word bytecode () const
label_t label () const
Kind kind () const
Instruction inst () const
uint16_t primaryArg () const
uint16_t secondaryArg () const
Static Public Member Functions
static Entity Label ()
static Entity Goto (const Entity &label)
static Entity GotoIf (const Entity &label, bool cond)
Private Attributes
Kind m_kind
label_t m_label { 0 }
Instruction m_inst { NOP }
uint16_t m_primary_arg { 0 }
uint16_t m_secondary_arg { 0 }
Static Private Attributes
static label_t LabelCounter = 0
Detailed Description
Definition at line 35 of file Entity.hpp.
Constructor & Destructor Documentation
Entity() [1/3]
Ark::internal::IR::Entity::Entity (Kind kind) explicit
Definition at line 5 of file Entity.cpp.
Referenced by Goto(), GotoIf(), and Label().
Entity() [2/3]
Ark::internal::IR::Entity::Entity (Instruction inst, uint16_t arg = 0) explicit
Definition at line 10 of file Entity.cpp.
Entity() [3/3]
Ark::internal::IR::Entity::Entity (Instruction inst, uint16_t primary_arg, uint16_t secondary_arg)
Definition at line 15 of file Entity.cpp.
Member Function Documentation
bytecode()
Word Ark::internal::IR::Entity::bytecode () const nodiscard
Definition at line 44 of file Entity.cpp.
References m_inst, m_kind, m_primary_arg, m_secondary_arg, Ark::internal::IR::Opcode, and Ark::internal::IR::Opcode2Args.
Goto()
Entity Ark::internal::IR::Entity::Goto (const Entity & label) static
Definition at line 28 of file Entity.cpp.
References Entity(), Ark::internal::IR::Goto, and label().
Referenced by Ark::internal::Compiler::compileIf(), and Ark::internal::Compiler::compileWhile().
GotoIf()
Entity Ark::internal::IR::Entity::GotoIf (const Entity & label, bool cond) static
Definition at line 36 of file Entity.cpp.
References Entity(), Ark::internal::IR::GotoIfFalse, Ark::internal::IR::GotoIfTrue, and label().
Referenced by Ark::internal::Compiler::compileIf(), Ark::internal::Compiler::compileWhile(), and Ark::internal::Compiler::handleCalls().
inst()
Instruction Ark::internal::IR::Entity::inst () const inline nodiscard
Definition at line 56 of file Entity.hpp.
References m_inst.
kind()
Kind Ark::internal::IR::Entity::kind () const inline nodiscard
Definition at line 54 of file Entity.hpp.
References m_kind.
Label()
Entity Ark::internal::IR::Entity::Label () static
Definition at line 20 of file Entity.cpp.
References Entity(), Ark::internal::IR::Label, label(), and LabelCounter.
Referenced by Ark::internal::Compiler::compileIf(), Ark::internal::Compiler::compileWhile(), and Ark::internal::Compiler::handleCalls().
label()
label_t Ark::internal::IR::Entity::label () const inline nodiscard
Definition at line 52 of file Entity.hpp.
References m_label.
Referenced by Goto(), GotoIf(), and Label().
primaryArg()
uint16_t Ark::internal::IR::Entity::primaryArg () const inline nodiscard
Definition at line 58 of file Entity.hpp.
References m_primary_arg.
secondaryArg()
uint16_t Ark::internal::IR::Entity::secondaryArg () const inline nodiscard
Definition at line 60 of file Entity.hpp.
References m_secondary_arg.
Member Data Documentation
LabelCounter
label_t Ark::internal::IR::Entity::LabelCounter = 0 inline static private
Definition at line 63 of file Entity.hpp.
Referenced by Label().
m_inst
Instruction Ark::internal::IR::Entity::m_inst { NOP } private
Definition at line 67 of file Entity.hpp.
Referenced by bytecode(), and inst().
m_kind
Kind Ark::internal::IR::Entity::m_kind private
Definition at line 65 of file Entity.hpp.
Referenced by bytecode(), and kind().
m_label
label_t Ark::internal::IR::Entity::m_label { 0 } private
Definition at line 66 of file Entity.hpp.
Referenced by label().
m_primary_arg
uint16_t Ark::internal::IR::Entity::m_primary_arg { 0 } private
Definition at line 68 of file Entity.hpp.
Referenced by bytecode(), and primaryArg().
m_secondary_arg
uint16_t Ark::internal::IR::Entity::m_secondary_arg { 0 } private
Definition at line 69 of file Entity.hpp.
Referenced by bytecode(), and secondaryArg().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/IntermediateRepresentation/Entity.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/IntermediateRepresentation/Entity.cpp