ArkScript: Ark::internal::ImportSolver Class Reference
Ark::internal::ImportSolver Class Reference final
#include <ImportSolver.hpp>
Public Member Functions
ImportSolver (unsigned debug, const std::vector< std::filesystem::path > &libenv)
void process (const std::filesystem::path &root, const Node &origin_ast, const std::vector< Import > &origin_imports)
const Node & ast () const noexcept
Private Member Functions
std::pair< Node, bool > findAndReplaceImports (const Node &ast)
Visits the AST, looking for import nodes to replace with their parsed module version.
std::vector< Import > parseImport (const std::filesystem::path &file, const Import &import)
Parse a given file and returns a list of its imports. The AST is parsed and stored in m_modules[import.prefix].
std::filesystem::path findFile (const std::filesystem::path &file, const Import &import)
Search for an import file, using the root file path.
Private Attributes
unsigned m_debug
std::vector< std::filesystem::path > m_libenv
std::filesystem::path m_root
Folder were the entry file is.
Node m_ast
std::unordered_map< std::string, Module > m_modules
Package to module map.
std::vector< std::string > m_imported
List of imports, in the order they were found and parsed.
Detailed Description
Definition at line 15 of file ImportSolver.hpp.
Constructor & Destructor Documentation
ImportSolver()
Ark::internal::ImportSolver::ImportSolver (unsigned debug, const std::vector< std::filesystem::path > & libenv)
Definition at line 12 of file ImportSolver.cpp.
Member Function Documentation
ast()
const Node & Ark::internal::ImportSolver::ast () const noexcept
Definition at line 126 of file ImportSolver.cpp.
References m_ast.
Referenced by Ark::Welder::computeAST(), and findAndReplaceImports().
findAndReplaceImports()
std::pair< Node, bool > Ark::internal::ImportSolver::findAndReplaceImports (const Node & ast) private
Visits the AST, looking for import nodes to replace with their parsed module version.
Parameters
ast
Returns
Definition at line 59 of file ImportSolver.cpp.
References ast(), Ark::internal::Begin, Ark::internal::Node::constList(), findAndReplaceImports(), Ark::internal::Import, Ark::internal::Keyword, Ark::internal::Node::list(), Ark::internal::List, m_imported, m_modules, Ark::internal::Node::nodeType(), and Ark::internal::Node::push_back().
Referenced by findAndReplaceImports(), and process().
findFile()
std::filesystem::path Ark::internal::ImportSolver::findFile (const std::filesystem::path & file, const Import & import) private
Search for an import file, using the root file path.
Parameters
file path to the file containing the import
import current import directive
Returns
std::filesystem::path
Definition at line 176 of file ImportSolver.cpp.
References m_libenv, m_root, and Ark::internal::testExtensions().
Referenced by parseImport().
parseImport()
std::vector< Import > Ark::internal::ImportSolver::parseImport (const std::filesystem::path & file, const Import & import) private
Parse a given file and returns a list of its imports. The AST is parsed and stored in m_modules[import.prefix].
Parameters
file path to the file containing the import
import current import directive
Returns
std::vector<Import> imports found in the processed file
Definition at line 131 of file ImportSolver.cpp.
References Ark::internal::Parser::ast(), findFile(), Ark::internal::Import, Ark::internal::Parser::imports(), Ark::internal::List, m_modules, Ark::internal::Parser::process(), Ark::Utils::readFile(), and Ark::internal::String.
Referenced by process().
process()
void Ark::internal::ImportSolver::process (const std::filesystem::path & root, const Node & origin_ast, const std::vector< Import > & origin_imports)
Definition at line 16 of file ImportSolver.cpp.
References findAndReplaceImports(), m_ast, m_modules, m_root, and parseImport().
Referenced by Ark::Welder::computeAST().
Member Data Documentation
m_ast
Node Ark::internal::ImportSolver::m_ast private
Definition at line 28 of file ImportSolver.hpp.
Referenced by ast(), and process().
m_debug
unsigned Ark::internal::ImportSolver::m_debug private
Definition at line 25 of file ImportSolver.hpp.
m_imported
std::vector<std::string> Ark::internal::ImportSolver::m_imported private
List of imports, in the order they were found and parsed.
Definition at line 31 of file ImportSolver.hpp.
Referenced by findAndReplaceImports().
m_libenv
std::vector<std::filesystem::path> Ark::internal::ImportSolver::m_libenv private
Definition at line 26 of file ImportSolver.hpp.
Referenced by findFile().
m_modules
std::unordered_map<std::string, Module> Ark::internal::ImportSolver::m_modules private
Package to module map.
Definition at line 29 of file ImportSolver.hpp.
Referenced by findAndReplaceImports(), parseImport(), and process().
m_root
std::filesystem::path Ark::internal::ImportSolver::m_root private
Folder were the entry file is.
Definition at line 27 of file ImportSolver.hpp.
Referenced by findFile(), and process().
The documentation for this class was generated from the following files:
/Users/fola/Documents/ArkScript/Ark/include/Ark/Compiler/ImportSolver.hpp
/Users/fola/Documents/ArkScript/Ark/src/arkreactor/Compiler/ImportSolver.cpp