ArkScript: Ark::Optimizer Class Reference
Ark::Optimizer Class Reference
The ArkScript AST optimizer.
#include <Optimizer.hpp>
Public Member Functions
Optimizer (uint16_t options) noexcept
Construct a new Optimizer.
void feed (const internal::Node &ast)
Send the AST to the optimizer, then run the different optimization strategies on it.
const internal::Node & ast () const noexcept
Returns the modified AST.
Private Member Functions
void throwOptimizerError (const std::string &message, const internal::Node &node)
Generate a fancy error message.
void remove_unused ()
Iterate over the AST and remove unused top level functions and constants.
void runOnGlobalScopeVars (internal::Node &node, const std::function< void(internal::Node &, internal::Node &, int)> &func)
Run a given functor on the global scope symbols.
void countOccurences (internal::Node &node)
Count the occurences of each symbol in the AST, recursively.
Private Attributes
internal::Node m_ast
uint16_t m_options
std::unordered_map< std::string, unsigned > m_sym_appearances
Detailed Description
The ArkScript AST optimizer.
Definition at line 31 of file Optimizer.hpp.
Constructor & Destructor Documentation
Optimizer()
Ark::Optimizer::Optimizer (uint16_t options) explicit noexcept
Construct a new Optimizer.
Definition at line 7 of file Optimizer.cpp.
Member Function Documentation
ast()
const Node & Ark::Optimizer::ast () const noexcept
Returns the modified AST.
Returns
const internal::Node&
Definition at line 19 of file Optimizer.cpp.
References m_ast.
Referenced by Ark::Compiler::compile(), and feed().
countOccurences()
void Ark::Optimizer::countOccurences (internal::Node & node) private
Count the occurences of each symbol in the AST, recursively.
Parameters
node
Definition at line 70 of file Optimizer.cpp.
References Ark::internal::Node::constList(), countOccurences(), Ark::internal::Node::list(), m_sym_appearances, Ark::internal::Node::nodeType(), and Ark::internal::Node::string().
Referenced by countOccurences(), and remove_unused().
feed()
void Ark::Optimizer::feed (const internal::Node & ast)
Send the AST to the optimizer, then run the different optimization strategies on it.
Parameters
ast
Definition at line 11 of file Optimizer.cpp.
References ast(), Ark::FeatureRemoveUnusedVars, m_ast, m_options, and remove_unused().
Referenced by Ark::Compiler::feed().
remove_unused()
void Ark::Optimizer::remove_unused () private
Iterate over the AST and remove unused top level functions and constants.
Definition at line 24 of file Optimizer.cpp.
References Ark::internal::Node::constList(), countOccurences(), Ark::internal::Node::list(), m_ast, m_sym_appearances, Ark::internal::Node::nodeType(), and runOnGlobalScopeVars().
Referenced by feed().
runOnGlobalScopeVars()
void Ark::Optimizer::runOnGlobalScopeVars (internal::Node & node, const std::function< void(internal::Node &, internal::Node &, int)> & func) private
Run a given functor on the global scope symbols.
Parameters
node
func
Definition at line 44 of file Optimizer.cpp.
References Ark::internal::Node::constList(), Ark::internal::Node::list(), and runOnGlobalScopeVars().
Referenced by remove_unused(), and runOnGlobalScopeVars().
throwOptimizerError()
void Ark::Optimizer::throwOptimizerError (const std::string & message, const internal::Node & node) inline private
Generate a fancy error message.
Parameters
message
node
Definition at line 65 of file Optimizer.hpp.
References Ark::internal::makeNodeBasedErrorCtx().
Member Data Documentation
m_ast
internal::Node Ark::Optimizer::m_ast private
Definition at line 55 of file Optimizer.hpp.
Referenced by ast(), feed(), and remove_unused().
m_options
uint16_t Ark::Optimizer::m_options private
Definition at line 56 of file Optimizer.hpp.
Referenced by feed().
m_sym_appearances
std::unordered_map<std::string, unsigned> Ark::Optimizer::m_sym_appearances private
Definition at line 57 of file Optimizer.hpp.
Referenced by countOccurences(), and remove_unused().
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/include/Ark/Compiler/Optimizer.hpp
C:/Users/folae/Documents/Code/Big-Projects/ArkScript/Ark/src/arkreactor/Compiler/Optimizer.cpp